help topics for VCS configurables ( IDEADEV - 33672 ) 
Continuous integration image 
Remove unnecessary 2nd await 
Updated changelog 
Add missing class . 
PR didn ' t compile . . . 
updated plan 
f2812af f8477bd 
Reverts FMJ because necessary files were erroneously removed from it . 
ignore Update ' modules / apps / web - experience / export - import / . 
Update CHANGES 
fixed error on token session length getter 
LPS - 64994 Liferay Screens Compatibility screenshots 
Setting development version 
unused import 
Undo test 
5add84f b5572ee 
typo fix 
f5432e01 cd5825cb 
Attempts to improve the RTP packet queue / the audio jitter buffer with resepect to recovery when the queue / buffer is full . 
ignore Update ' modules / apps / foundation / portal - cache / . 
Do not start queued actions for TV device 
LPS - 48434 Add search_reader and search_writer threads to the synchronous approach 
I should probably use variables 
ignore Update ' modules / apps / web - experience / portlet - configuration / . 
b40108f d913d78 
Update README . md 
Use - F instead of cat 
Fixed unit test after rebase 
Updated changes log 
update changelog 
wip3 
ignore Update ' modules / apps / collaboration / document - library / . 
removed redundant ' pooled = true ' 
9d50308 26026c6 
Set the version of keymaster . js 
6083f5e 745b43c 
9563701 80fccb4 
Update README . md 
LPS - 61748 prep next 
several words were added 
Fix firestone build 
LPS - 54963 gradle sdk 
Fix config 
Translated using Weblate ( Danish ) 
don ' t build consoleio on win64 
Update gitignore 
pre - installed DemoAPI tests fail . . . 
change timeout for test 
Change support lib symlink in ABS directory to actual copy for Windows users . 
icon 
fix bintray publish per # 115 
 ' 0 . 3 . 8 ' . 
remove " throw " occasionally left while debugging . 
ignore Update ' modules / apps / web - experience / staging / . 
change the test redis version to 2 . 8 . 24 . 
LPS - 66282 Increase app server startup timeout to 15 minutes to match ant 
Add more fiels to gitignore 
add missing file 
Cache ~ / . 
revert jline dependency to 2 . 11 until fix is available for 
ignore Update ' modules / apps / foundation / xstream / . 
Source formatting 
Missed line break 
12c20dae 3d8e46ec 
Ensure that JAR files in libs directory are included 
obsolete 
update server metrics version 
Update . 
missing fields for automcompletion 
Fix launcher icons 
Delete ic_launcher . 
gitignore files added . 
Clarify usage of StateManagerExceptionHandler . error field with a comment 
add # 5125 to CHANGES 
Fixed Checkstyle error 
Temporarily disable MixinC00Handshake 
97672e22c a731d835c 
Updated webpack / react profile versions 
Don ' t draw synchronously in onResume ( ) 
fc5a760b 9f0d7c53 
Update to match Spring 1 . 2 - RC2 ' s Hibernate version . 
LPS - 20721 Disable for now 
update to latest class name , I believe . 
7645062 0821f27 
update windows natives 
fixing indentation issue 
d1e5dda 5785355 
use 2 . 0 . 0 - beta7 
fix CAMEL - 482 . 
Add groovy console support for the tests , to allow debugging of the AST . 
Update master 
66360ac baa2812 
Move compiler std back to gnu99 . 
update contributor list , add yaphet , bjlindeqiang , dingjun , Dollyn , feilaoda 
Update Gradle plugin to 0 . 14 for compatibility with Android Studio 0 . 9 . 0 
Update version number in build . 
Removing the verbose flag . 
Update README . md 
install - > package 
THIRDEYE - 320 Publish shaded jar for thirdeye - server 
27dfd01 e2d3156 
expose self ( ) to subclass . 
Delete outdated directory creation in build . xml 
trival fix to remove a 0 byte file 
9a79680 023f8e0 
setting version to 1 . 0 . 119 - SNAPSHOT 
Translated using Weblate ( Danish ) 
Translated using Weblate ( Portuguese ) 
Caffeine 2 . 3 . 4 . 
Record 
bea76ea 32a9cd8 
README 
moved WhoAmIBean 
ignore Update ' modules / apps / foundation / configuration - admin / . 
executable ON gradlew 
Remove warning that should rarely matter 
Correctly close the context action mode when deleting an account . 
back button in greent does not work properly after the second usage . 
41ac0d9 134f3c2 
9c9e22c0 0fe32877 
LPS - 9014 Source formatting 
Pair made covariant 
Add screenshot 
Mark test as NOPASS . 
add HDFS - 7419 
Fix xml error 
LPS - 42669 Template cache does not work caused by LPS - 41375 
Dictionary extended 
added * . 
prepare release checkstyle - 7 . 2 
Fix simulator build . 
ignore Update ' modules / apps / collaboration / microblogs / . 
Cylinder pattern was missing the name 
Create . 
Remove lib / scala - library . 
Upgrade to Flow 0 . 2 . 98 
Gradle 2 . 3 . 
Removed obsolete file 
b64e0f9 87f86e6 
added a method to identify a classnode as interface 
Join the developers list in the pom and fix the client run configs in the workspace . 
fix typo step two of two 
Upgrade AutoValue from 1 . 0 to 1 . 2 . 
update changelog for STORM - 507 
add sample apk 
made checkstyle happy 
Remove file that was accidentally checked in . 
Version 1 . 3 . 1 . 
Removed tag roboguice - 2 . 0 - ignoreme2 
LRQA - 19035 prep next 
LPS - 53621 - Updating Alloy 3 . 0 . x to 00f99b77f1af2aefe70558917b503cd9c7d4104e 
Fixed pom . xml issue with distributed sub - project 
make the compiler available to subclassses 
Configured travis to build with docker . 
Updated changelog 
built from latest source and included src into jar 
failed locally but not in build ! 
switch to plugin pom 
Updated changelog 
Exclude NoFrom test from hsqldb 
Version 1 . 3 . 0 - rc - 1 . 
Upgrade from JMH 1 . 12 to JMH 1 . 14 
LPS - 55176 - Updating Alloy 3 . 0 . x to 6a58e7bd1fc6510472e65039a827b76e241aac5f 
use . 
todo list 
snapshot 
ignore Update ' modules / apps / collaboration / blogs / . 
32d6914 9667c28 
Changed location of section for better look ` n ` feel 
up version to 0 . 1 . 63 
release 2 . 2 . 5 
remove the final modifier to ensure it will compile again 
indri lib 
Bump version 
update UpcomingChanges 
GPS battery tracking . 
e9a320c 82e55f6 
Create . 
Added . 
ignore Update ' modules / apps / marketplace / . 
LPS - 65283 update jar 
Update reference to library after merging share update in it 
LPS - 4464 Apply panels to Web Form Configuration ( Fixes mistake in last commit ) 
ignore Update ' modules / apps / foundation / users - admin / . 
try to fix error when querying for browser type 
6754f68 e820087 
 ' hystrix - 1 . 1 . 7 - SNAPSHOT ' . 
Fixes NullPointerException on creation of Jabber account through the initial account creation form . 
Version 1 . 3 . 0 - rc - 2 . 
use Gradle application plugin to create a starter script 
try screen refresh 
ignore Update ' modules / apps / foundation / web - proxy / . 
6f71159 c104e1b 
getEnv ( ) visibility fixed 
9875b571 06ff4c7 
update dff image . 
Adds readme 
no_reply @ jetbrains . com < Igor Kuralenok > 
divided in 2 
Examples for release 156 
Fix reference to mustfix in RCTLog 
Update SpongeCommon 
CHANGELOG entry for 1329 
f6530adb3 5ba8ac20b 
dynamic - data - mapping - form - values - factory 2 . 0 . 0 packageinfo 
Build in travis with oraclejdk8 
removed unused imports 
Fix for IDEADEV - 1142 
Update library reference 
Let it accidentally slip on CVS . 
add more notification images 
the new snack bar hide too quick if clear previous snacks . 
Bump version code 
fix for network proxy factory 
remove extra thumb directive from trampoline 
91f2a7c 6888bee 
Update common for registry fixes . 
9e5d683 3b65983 
Enable parallel Gradle builds for Travis 
Build the dummy jar with target compatibility 1 . 6 . 
Smack 4 . 0 . 3 - SNAPSHOT 
Kickin ' Travis CI to work again 
Update project . properties 
Shorten the zen supertoast visible duration . 
cleanup 
expose the highlighter builder Field constructor 
LPS - 44465 - Source formatting 
Changelog entry 
prep for dev 
LPS - 47516 wait for system search engine to be present before initializing 
Nicer whitespace 
Accidentally set env as matrix 
unix lexer creation script 
ignore Update ' modules / apps / collaboration / microblogs / . 
update ignore 
Record 
Update build - config parent version 
line break 
LPS - 27831 Source formatting 
4c5627b84 53953b14c 
Invalid constructor call in a test causes all CI failure 
update readme 
ignore Update ' modules / apps / foundation / frontend - js / . 
Run only on jdk7 for the moment 
8040d6f 215ecb9 
service START_REDELIVER_INTENT 
e43f57e 48db5c5 
update asmack to new commit 
adding newly created eclipse config file 
added TODO 
ignore Update ' modules / apps / web - experience / site / . 
snapshot version 
fixed typo in tag of word * cis * in manual tagger . 
Remove 888 
LPS - 46252 Match org - apache - commons - fileupload 
Updated library name 
Added my version of dll with memory fixes 
Update ' modules / apps / foundation / map / . 
Fixed compiler warning about next / hasNext selectors . 
ignore Update ' modules / apps / web - experience / layout / . 
LPS - 31159 Move TemplateResourceExternalizationTest to portal - impl / unit - test 
Create README . md 
FramebufferNativeWindow . h is obsolete 
Updating Alloy 
Make bilingual text visible for city 
Close ResponseBody on 204 / 205 to avoid connection leak 
Updated changelog 
Add eukaryote / eukaryotic 
Have a bottom actionbar in the Search activity to be consistent . 
Updating logo 
ignore Update ' modules / apps / foundation / users - admin / . 
add icon for JWS 
Typo 
Fixing CLI to pass " sourcemap - output " option to bundler . 
Add out / directory to . 
Upgrade to parent 20 
Remove @ nosideeffects from DataTransferItem . prototype . getAsString ( ) 
Increase default training time 
Back up / restore the ' mono audio ' setting 
README update . 
Moving all big data tests to hdfs - bigdata directory 
Added jme3 - lwjgl3 / build / to the gitignore file . . . . 
Bump version to 0 . 19 - SNAPSHOT 
Fixed typo in FlaggedClientConfig file name . 
Fixed . 
ignore Update ' modules / apps / foundation / portal - settings / . 
update 
LPS - 30823 Source formatting 
hide clear button on focus lost 
Fix external non - git source builds 
Add TBD NEWS entry 
aea9c66 9dd65b9 
Add http timeout as well as socket timeout 
item - selector - api 2 . 0 . 0 packageinfo 
Dev commit . 
pushed version 1 . 0 . 1 to maven 
Update common ref 
wat . 
remove check for Java 6 or above before applying bintray . gradle 
better clean ( another attempt to fix PY - 4072 ) 
LPS - 53386 It is needed to export this dependency 
be consistent for setter 
LPS - 55364 make it private since it ' s still needed 
Record 
add link to stack overflow 
RenameJavaVariableProcessor . prepareFieldRenaming 
Tweak appveyor build 
upgrade maven ant tasks to 2 . 0 . 10 
Modified . 
Update SpongeCommon for GameProfile helpers 
Update README . md 
added JavaScriptCodec 
Minor fix 
projeto pronto para ajustes 
Record 
ignore Update ' modules / apps / foundation / frontend - js / . 
add # 4494 to CHANGES 
removed the version number from the license ( too much of a pain to update ) 
setting version to 1 . 0 . 81 
fix memory leak 
Category changes 
Update SpongeCommon ref . 
site is uploaded to github upon release phase 
 / / nutz . googlecode . com / svn / trunk @ 24 423f10f2 - e3a4 - 11dd - a6ea - a32d6b26a33d 
Record 
update sunos - x86 * natives 
Adding pr template 
Added STORM - 1128 to CHANGELOG . 
725267198 db56d8249 
Recompile svm . java and lisvm . jar . 
Call progress ( null ) in closeOutput ( ) 
more collision stuff . . . 
Remove the LightSpace entry in Lighting . j " md as it not needed anymore 
bundler version 
Update version to 2 . 0 . 1 
Fix wrong argument of StandardWrapper . remove ( ) in case when singleThreadModel and instancePool are used . 
travis updated 
Remove x bits from java files 
fix changelog for 6 . 0 . 1 ( # 95 ) 
Add 111 
Update to 8 . 0 . 9 . 
prepared for next development iteration 
Pic 
d19cf27 330865d 
removed package statement as we ' ve stuff in groovy . 
add analysis - stempel module 
LPS - 64319 Semver 
Updated documentation for segment tree 
set for release 
fb6dbe85a a0802b7d4 
Quick fix - revert ADD line 
LPS - 56041 shouldn ' t need this 
remove offending . 
ignore target 
LPS - 47839 On mobile devices documents and web content titles are cut off in icon view 
Adds some scala compliation cache files to . 
PREPARE RELEASE v2 . 0 . 2 
Remove auto permission request from setAppIconBadgeNumber 
sp 
ignore Update ' modules / apps / collaboration / wiki / . 
ignore Update ' modules / apps / collaboration / wiki / . 
Remove removed jdic leftover 
background . gif for minimal javadoc style adjustment 
fixed migration - create script 
ignore Update ' modules / apps / collaboration / item - selector / . 
Fix timezone for Launchpad 
Update Graphics 
update 
Fixing the layout so that instead of wrapping , it is set to fit the contents 
f66b219 842b914 
ignore Update ' modules / apps / web - experience / staging / . 
LPS - 46283 - properties 
Revert aspectj to default version 
cool Hudson , you actually think nothing has changed in SVN ? 
Record 
ignore Update ' modules / apps / foundation / portal - settings / . 
Set default encoding to UTF - 8 ( fixes # 192 ) 
Remove an overzealous call to setDefaultSelection . 
Language keys for 5 . 2 . 
don ' t let the page become overly wide - improves readability 
add out to gitignore 
2df91b7 f7e6415 
LPS - 46862 - dependencies 
new PyCharm Mac icon ( DSGN - 56 ) 
LPS - 56792 sdk 
Fix a Javadoc comment . 
fix javadoc error on getAt ( Map , Object ) 
Record 
Sync 
721a7b78d 2c8f1a78e 
Factory should not be synchronized . 
correct spec version dependency 
Typo 
Fix wrong states when waking up from doze via touch 
Release 0 . 106 
Format fix 
ignore Update ' modules / apps / collaboration / blogs / . 
IDEA - 88587 ' Annotate ' action from popup menu in File History table is always disabled for Git 
revert version 
added standard intellij omissions to . 
setting version to 1 . 0 . 95 - SNAPSHOT 
Bump up RC version release 
removed @ Property 
f5d4128 f4565a9 
Remove unused import 
pom version change to druid - 0 . 2 . 27 
abce77c 70de03d 
format data chunks using format not as . character 
ignore Update ' modules / apps / collaboration / blogs / . 
Add missing value for @ JsonProperty in documentation 
486232d6 6978a34c 
Bugfix for oracle upgrade script . 
Removed maxReturnCount from checkstyle . 
V1 . 1 
Updated version code 
Update README . markdown 
Fix issues with video on linux . 
add migration for adding metadata for each secret version 
Removed a file that has a wrong case of the parent folder 
Make sure that we close the chat window with escape ( temporary fix before we move to a text file ) 
remove legacy jar download 
css for standalone images 
ignore Update ' modules / apps / collaboration / bookmarks / . 
move logos to website ( # 705 ) 
LPS - 20444 Source formatting 
20333bb46 4b7530135 
removing the pxfetcher module from the gradle settings 
added screenshot 
Reverts revision 83 because it causes receive streams to stop ticking . 
Update Readme 
Update gradle . properties 
Prepare version 21 . 0 . 4 . 
ignore Update ' modules / apps / foundation / users - admin / . 
Remove import of removed view . 
e9b38f4 f98e168 
d5924e9 23c907c 
 ' ribbon - 0 . 1 . 5 ' . 
Add placeholder for manual page about streams . 
d3473ff a6dea12 
test svn commit 
Updating Alloy 
Make sure the mExtraState array is not null 
Diagnostics project doesn ' t need cunit for int tests any more . 
Next iteration 
Bump Version to 0 . 3 . 9 
Add missing test resource 
Fix Build 
LPS - 65492 Ignore SF for now 
2842bd0 8a927cf 
HHH - 7128 Upgrade to Infinispan 5 . 1 . 2 . 
add ' goto ' to dictionary 
remove circular symlink 
Mark # 1399 completed ; some aspects remain , but initial implementation should now work well . 
added SONY Ericsson Xperia Play 
 ' 0 . 7 . 7 ' . 
enable coverage to work with java 8 ( IDEA - 96364 ) 
ignore Update ' modules / apps / foundation / frontend - theme / . 
add words suggested by users 
Update README . md 
Travis should build 4 . 0 branch for now 
bump local threads 
e74050a d3f00f9 
fix Win32 build break ( missing comma ) 
Updated test for GROOVY - 3401 with a correct example showing that we can put a blankline before the colon 
Spring mock is required for compilation 
Update README . md 
 ' ) " 
Added TSV test file for 
42c1120 8f14969 
Update SpongeCommon for InteractBlockEvent fix . 
increase heap memory 
7519dce ee5a181 
Joe Bowser < Joe Bowser @ bowserj - win7box . adobenet . global . adobe . com > 
Update gradle . properties 
3e21228 cafbb09 
version of gradle check 
Fixes a problem with RTP timestamps not being properly computed for Opus . 
updated pac4j version to the released 1 . 8 . 2 
Update LICENSE . txt 
fixed typo in comment 
reverts back to java 1 . 6 
Latent risk of infinite recursion due to typo in QueryPartList . retainAll ( ) 
Version 0 . 10 . 67 ( code 167 ) 
70ab0dae 1b8d10fb 
3619290cf aebf2e120 
Added horizontal barchart . 
Fix build 
Bump version to 0 . 0 . 7 . 
Set version 0 . 13 
Ensure only a single scroller animation callback per frame . 
Add FIXME notice for dirty hack . 
update . 
Set touch mode to be TOUCH_DONE_MODE when calling doDoubleTap . 
new mac java app stub 
ignore Update ' modules / apps / collaboration / document - library / . 
update to 6 . 13 - SNAPSHOT 
LPS - 13277 Editable should unescape HTML entities when set input value 
Removed white spaces 
MinecraftForge / FML @ b2958c9066db8c95bb4260893fbfe00103fc4ba1 Add quotes for paths with spaces - . 
Release v0 . 87 . 0 
9c2dbbf 9095409 
cleanup 
new v 
 ' 1 . 1 . 127 - SNAPSHOT ' . 
updated from transifex 
let graceful test layers bind to localhost instead of any 
changed version to 0 . 9 for public release 
update ignore 
LPS - 28872 - Updating Alloy to d67fc56 
looks lile Enum doesn ' t work , try enum 
97a22e1 92671e5 
ignore Update ' modules / apps / foundation / configuration - admin / . 
cleared cache in travis 
Update to a Maps dependnecy from this decade . 
Default http timeout to PT5M 
Changelog updated . 
update apk name 
Added maven . src . dir property to point to src / main because of changed m2 directory structure 
release 2 . 1RC3 
Getting rid of some unused and deprecated code , added in a comment to help explain and separate the partition shuffling 
Update jackson to 1 . 7 . 0 ( seems to get 10 - 15 % performance improvement ) 
clear ( ) 
3048f44 0174476 
Cleanup 
LPS - 56798 - add . 
reset current scheme panel after import if current scheme was updated 
ff362226e 10f7ba2ee 
Removed unused import 
change to notest . 
ee53d3c4 f8a15a41 
Bump version number 
spelling . txt - - added female forms of ' Staplerfahrer ' 
Update gradle scan 1 . 3 ( # 212 ) 
Increase timeouts in example config . properties file 
Added OS - specific line endings for . 
80ee849 d0d2a67 
9a9bc9b 6b183e9 
Smack 4 . 1 . 0 - rc2 
Fix the dock - insertion Dream entry codepath . 
ignore Update ' modules / apps / foundation / portal - security / . 
Re - record OSS snapshot tests 
4fdfdee f98ab8b 
Add readme . md 
bezier 
prepare release acra - 4 . 6 . 1 
Added John Wagenleitner to the contributors 
travis - ci cache maven 
updated extendedset version 
 add Yao Wei in AUTHORS 
Update version number 
Add image for padding and margin 
9dde47a2 75f859c2 
CORE - 405 Problem with Firebird supporting DDL in transaction 
rolled back to 0 version 
Guava r08 . 
Add javadoc link to readme 
trivial 
update NEWS 
LPS - 62715 add build . xml 
Record 
workaround for missed capture parameter 
LPS - 48540 
remove obsolete xsd 
Added translation using Weblate ( Basque ) 
Nicer screenshot 
Comment for travis 
There ' s no git submodule used any more . 
setting evicted was ' little ' more aggressive 
658bec9 9283f3c 
Updating Alloy to f98b1d9 ; LPS - 18541 
Update README . md 
Bump up version number . 
Upgrade parent to 22 
82d7f4e 39e8061 
Groovy Console Icon for Mac OS X broken 
501209d d3f2657 
Previous cleanup missed one string 
turn off auto check for hockeyapp updates 
Added debugging flag to build to find cause for API failure . 
9450fac 576b6f2 
bumping version 
LPS - 50018 SF 
Support quatation mark for text command 
1e2b63d 02b115b 
Make InconsistentArrays an error 
Updated version 
Add ` repositories { mavenCentral ( ) } ` to Gradle instructions for completeness 
ignore Update ' modules / apps / collaboration / blogs / . 
Update SpongeCommon ref . 
a4507bb 707d54c 
try to fix failing CI 
bump version 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
049ede5 0639795 
1c89af1 ff2184e 
LPS - 27138 Avoid nullpointer exception in tests 
ignore Update ' modules / apps / collaboration / announcements / . 
portaudio when creating ZrtpFortunaEntropyGatherer . 
3f9ef8d 36818b3 
17f3cdc 1f14863 
activate email notifications 
ignore Update ' modules / apps / foundation / frontend - editor / . 
LPS - 30768 
Revert accidental commit in r1541472 
ip - geocoder 2 . 0 . 0 packageinfo 
Try using gradle not wrapper which might require sudo 
LEP - 1451 Upgrade EasyConf 0 . 9 . 5 
Add some meat from our results to the abstract 
Update build 
Warning in documentation for deprecation of rivers 
remove accidental System . out . println 
a1b4d97 019118a 
add a shutdown method to shutdown the executor service 
LPS - 55159 Generate 
LPS - 56973 sdk 
publish artifacts to kaeppler / maven2 
updated version 
Update Bleeding Edge version from 3 . 7 . 0 to 3 . 9 . 0 
f8627d6 577a253 
disable sudo 
Renamed Zoomable Example app 
HHH - 5356 Sybase 15 does not support cross join 
prepare for next development iteration 
Added message . 
Ignore Screenshots dir . 
Version 1 . 4 . 3 . 
change default split size to 64 M in python tool script . 
change the key alias from tomcat to jboss . 
Get rid of encrypted_secring 
Ignore lint . 
Set encoding to utf8 to get rid of javac warnings 
Prepare next development version . 
LPS - 56407 sdk 
test for commit . 
add platform info to libclang diagnostic function 
removed nested namespace 
Update README . md 
8db6d9a d93b0b6 
Add contributors to haskell port 
Update version . 
LRDOCS - 2547 Remove old doclet JAR that is no longer used . 
Next Development Version 
ignore Update ' modules / apps / foundation / portal - search / . 
LRQA - 27552 prep next , use latest 
Add an explicit Window . prototype . Window to prevent the renaming of window . Window 
localization diagram by Xie 
Fix type 
tweak of bbb_banner . 
ignore Update ' modules / apps / web - experience / product - navigation / . 
ignore Update ' modules / apps / collaboration / bookmarks / . 
version bump 
ignore Update ' modules / apps / sync / . 
Fixed path of prefixes . properties path . 
Remove completed TODO 
Updating the changelog for v1 . 0 . 1 . 
added composite class diagram 
moved doc page to the installation directory 
Update README . md 
ignore Update ' modules / apps / web - experience / product - navigation / . 
make inner class static 
Source formatting 
Add service definition so ServiceLoader picks it up 
add new logo to resources 
Remove debug output 
LPS - 52611 Rename file 
508286c cffc172 
Moving class to dp package 
added print stack trace 
Copy across the XML files to be in the classpath . 
 ' 1 . 1 . 116 - SNAPSHOT ' . 
dd6b749 dac2980 
Both log4j - over - slf4j . jar and slf4j - log4j12 . jar in the management webapp 
Up the version num 
Adding STORM - 1143 to CHANGELOG . md 
Add glyphs for Vertical Text 
Ha . . . useful to be able to get the size of a stack . . . 
added smooth ( ) and noSmooth ( ) to syntax highlighting . 
LPS - 56233 sdk 
Update changelog for RB = 154319 
Fix failing snapshot test 
LPS - 30680 
LPS - 10604 Source formatting 
Default to non - smooth scrollbar . 
27227b0 2980796 
Update SpongeCommon for client jitter fix . 
Delete HBase daemon logs as part of ` mvn clean ` 
 ' 0 . 13 . 1 ' . 
8473bc8 810c655 
0f7c057 61a7f61 
remove U + 261d from MTLmr3m . ttf 
ignore Update ' modules / apps / collaboration / blogs / . 
8e27167 2d1af2c 
Add missing @ Override 
Prepare for 1 . 1 . 0 release 
 ' 0 . 4 . 49 ' . 
Changes . 
Recalculate orientation in getOrientation ( ) 
Update JPA - Ticket - Registry . 
Fix broken test . 
Minor fix . 
possible to choose Main class from a library 
update to latest FastAdapter v1 . 0 . 5 
Don ' t abort build on lint errors . 
woops java type checks ! 
864edfdaf faf0d902f 
7b737c8 686a1b2 
 / / github . com / yole / colorSchemeTool 
prepare for next development iteration 
LPS - 52141 SF 
LEP - 5922 - refactoring , see comments on ticket 
fix testdata 
Run core tests in alphabetical order 
Ignore Google Play Services warnings due to missing Apache client . 
Update plugin 
Actually submitting the right number . 
about those fonts . . . 
remove unnecessary import 
LPS - 48373 SF 
Version 0 . 10 . 65 ( code 165 ) 
8d3e1031f 7cb1ec0ec 
Forgot to check in latest version of menu - dropdown . 
last tidbits 
Bump version 
add note on probable bug 
added Lenovo ThinkPad Tablet 
Add webkitFullscreenElement to Closure ' s html5 definitions . 
Don ' t try and build the project when running ` . 
LPS - 35473 SF 
use smaller font size for outline 
Update README . md 
LPS - 53175 SF 
Make shuffle + x 
fix travis build 
Prepare for v1 . 5 
ignore Update ' modules / apps / collaboration / blogs / . 
Record 
add STORM - 1771 to changelog 
ignore Update ' modules / apps / web - experience / site / . 
temporary S2 repository for reactor 
Revert previous change setting ONLY_ACTIVE_ARCH . 
Add sample apk 
Updated FAQ 
Update . 
45dd12c 4b4f40f 
Simplify definition of integ test compile classpath . 
Added translation using Weblate ( Azerbaijani ) 
fix a bug in commonutil . 
Bump common ref . 
Replace image for layotu practice session 7 
inline global context accessor 
Update SOURCES 
6ea71d6 f81a2f9 
edit changes 
Add binary attribute to generated built - ins data 
Improved template method UML . 
 / / www . jetbrainsdotNet / jira / browse / IDEADEV - 1802 
Version 1 . 0 . 16 ( code 188 ) 
4a53b51 48d1dac 
Fixed wrong separator path in project . properties 
Removed unused images 
gradle plugin version bump 
Disabling warnings about issues relating to the use of command line options during compilation . 
Readded 24 hr ( # 86 ) 
Reverted gradle plugin upgrade due to weirdness . 
release 
ignore Update ' modules / apps / collaboration / microblogs / . 
Fork tests 
release version 
50aded0 384b5d2 
Need to install the gradle plugin before running its tests . 
Source formatting 
Updating Alloy to da42f89 ; LPS - 30946 
Update to use GCC_OPTIMIZATION_LEVEL instead of OPTIMIZATION_LEVEL . 
 ' hystrix - 1 . 0 . 2 ' . 
53c1bbf 5fa782c 
Now that our not - deleted - messages mode works , actually use it in messagelists 
LPS - 39177 Adds css class missing space 
97ba0a0d 313baca8 
Update README . md 
ignore Update ' modules / apps / collaboration / social / . 
HHH - 7280 Upgrade to Infinispan 5 . 1 . 4 . 
ignore Update ' modules / apps / collaboration / wiki / . 
Enabled java builds on travis - ci 
ignore Update ' modules / apps / foundation / frontend - js / . 
LPS - 61383 prep next 
40c38de 5a78571 
Updating to Alloy 1 . 0 . 1 - rev . 59522 
grayed text is invisible on Linux 
Remove terminal pointer incrementaion 
Updating Alloy to rev . 67396 
copy resources , even in test source roots 
Ignore AS v1 . 5 captures / folder 
 ( cqlsh ) Fix default CQL version 
Point default duration 
fix typo 
update bundled JRE to 1 . 7u51 , refs OF - 513 
Update gradlew to 2 . 2 . 1 
020e39f39 e47e03814 
private constructor added 
LPS - 45283 
Import icon 
Version 0 . 10 . 56 ( code 156 ) 
IDEADEV - 7872 
test commit 
update jar 
Fix bug 43706 . 
conditional signing 
Updates ice4j to r476 ( fixes a possible NullPointerException ) . 
Parser now uses new colvalue instea value . 
new image changes 
dd914cc 1e13754 
Update README . md 
Update API . 
r / m empty file 
escalate visibility 
Fix build 
812ccbe ab67fb9 
Inserts protocol property for correct custom SIP providers handling ( ippi wizard , sip2sip wizard and so on ) 
Fix InsecureApplicationTests package 
bump version up - 0 . 9 . 2 
Removed home made Groovy JSR - 3 snapshot . 
Outdated version of javaee_web_services_client_1_2 . 
12757d149 45ab6d245 
New section added to index . 
LPS - 61577 prep next 
 ' ribbon - 0 . 1 . 7 ' . 
add README . md for grails - codecs 
0492199 779321f 
Removing empty test 
Trivial commit - explicitly exclude build / rat - report . 
c6d83ca 5f866a4 
working on multi chat and a jabber implementation 
c518080c 7198030 
LPS - 49936 sdk 
Fixing build framework script 
removed built in color from layout 
change version num and year for the release of libsvm 3 . 15 
fix ( android ) disable lint 
Add travis . yml 
Caffeine 2 . 3 . 5 . 
Fix typo . 
f5c892f ba87519 
Remove sudo brew ; no longer supported ? 
Added New Context dialog 
Update . 
Translated using Weblate ( Catalan ) 
add left out part of parser 
Set version v0 . 4 . 2 . 
Fix the message decoder to ignore reserved flags 
prepared IDEA X eap logo 
gitignore for IntelliJ IDEA files 
 ' async ' added 
Pushing v13 android support package 
9359220f9 a29a84833 
new jikes for osx 
Do not update accessibilityTitle in 
LPS - 65225 add KB 
ignore Update ' modules / apps / marketplace / . 
Prepare for v0 . 8 . 9 release . 
Updated changelog 
add demo gif 
fb25631 ca9904d 
Disabble vertex logging . 
fixup ! 
ignore Update ' modules / apps / foundation / portal / . 
ignore Update ' modules / apps / foundation / frontend - editor / . 
Sample update 
7526a6d a66cee1 
Accomodate changes in the render signature in the RajawaliScene class . 
bd57eea d97b7f2 
ignore Update ' modules / apps / foundation / portal / . 
fix broken example 
ignore Update ' modules / apps / foundation / configuration - admin / . 
bbd460d 69e19ae 
CHANGES . txt 
Update AVS to 3 . 1 branch . 
Make the classpath manifest cacheable 
test fixed 
Initial Plugin commit 
added missing build . properties file for MAX ! Cube test project 
6d86307 1187c7a 
added helper method for builder implementations 
HHH - 7176 Upgrade to Infinispan 5 . 1 . 2 . 
LPS - 35210 Autocomplete should be enabled by default 
ignore Update ' modules / apps / foundation / portal - search / . 
removed . 
started to fix mdi windows edge buttons 
build number baseline set to 146 
f3ff29d 8ac58f4 
Changed version of spring - mock to 1 . 2 . 7 for consistency . 
Update README . md 
Ignore IntelliJ files . 
Updated to new snapshot 
 < dev - null @ apache . org > 
Trivial formatting 
 / / github . com / facebook / react - native . git 
git ignore all files in scripts / patches 
latest jar file 
ec42199 90840ec 
upgrade to 0 . 7 . 3 
Removed old license 
Gradle plugin 2 . 0 . 0 - beta - 2 
bugfix for sqlparser 
21091e8 feafc99 
remove blank line 
ignore Update ' modules / apps / collaboration / wiki / . 
update multiwords . txt 
Roll back to gradle 2 . 1 . 2 to fix builds . 
LPS - 56834 sdk 
4efc4a1f 28cb07cf 
scope added 
upgrade maven ant tasks to 2 . 0 . 10 
Fixes the path for cd command 
Updating README 
Update README . md 
5d1f2c1 9bcd20f 
Updated changelog . 
0a33c4f 7866f2f 
afd0936 b8b4e85 
2474ebe aa43eb5 
ignore . 
 / / issues . apache . org / bugzilla / show_bug . cgi ? id = 49141 
remove unnecessary line in test fixture 
fix for build failure 
3590cff0 174c8b2b 
Set constructor properly in createReactNativeComponentClass 
Get rid of unused imports . 
test scala code 
Bump Netty version 
PyCharm 5 . 1 Beta artwork 
update screenshot 
Changed permissions on run_example . 
prep for dev 
Reset scroll position when clear state 
Used new Travis infrastructure 
Ignoring bin folder 
Update graylog2 - plugin version in pom . xml 
update changes for f8a30caae253c8201b403eeb0651b9e1d9d799a5 
test lately fails occasionally on the build server so give it some more time 
Hi , I ' m SpongeForge 
Prepare next development version . 
6161c5b 67abeef 
f561e21e2 3d13d634a 
update jarjar to release version 
Make tagNameFormat of release plugin consistent with our tag schema 
LPS - 38465 
ignore Update ' modules / apps / collaboration / document - library / . 
eaaa21bd1 3c91608a3 
35b1674 cd03be6 
rc - 3 version bump 
Dave ' s wav file 
Wrong method name 
ignore Update ' modules / apps / foundation / license - manager / . 
Update h2oFlowVersion to 0 . 2 . 6 . 
LPS - 55111 prep next version 
update todo comments 
update NEWS 
Back to the initial aggressive id - reuse batch size 
Announce changes to the keyguard security message for accessibility . 
LPS - 60633 ( SERVICE ) move service . xml 
Removed all big dataset tests 
 - Create a passive rule which detects big redirects ( Revert unnecessary commits r5352 and 5351 due to forgotten 
Update README . md 
Locals should be empty in console from default . 
same output file as scala / java examples 
Closure to make lazy dependency on subprojects . 
Return carrier label to notification panel . 
Chinese translation . 
test - > tests in makefile tags 
typo 
GRAILS - 6760 - fix javadoc 
To JB dic 
a few more recent examples of what LT can do . 
Fix log version string . 
Call moveQueueItemHelper instead of moveQueueItem 
Upgrade to netty - build - 16 
2015f11 3890a8d 
added help for filter ' Send ZAP session request ID ' 
Logic bug fix . 
Update secure token . 
Update SpongeCommon 
Fixed a hang in case of some connection exceptions ( PY - 14829 ) . 
git ignore fixes 
LPS - 69453 Keep old jar name 
Fix dll location search . 
Rerender message bubbles on encryption change 
LPS - 53177 SF 
873884a7 603179e9 
Translated using Weblate ( Danish ) 
Latest snapshot of trakt - java , including sources . 
vs rest , single digit binomial GLM for mnist training data , checking the actua 
Updated for 4 . 0 - beta5 . 
Java 6u15 for Windows 
fix testData related to JvmName retention 
dll - > pyd 
Split taglib between servlet specs 2 . 3 and 2 . 4 . 
prepare release v1 . 1 
try diagonal NR shader of same density 
don ' t need see 
version bump to 1 . 4 . 7 
Two dependencies on junit found . 
ignore properties ( via phunt ) 
fix build , remove briefdocs 
update tutorial to create db utf8 by default 
LPS - 56021 Bump up module lock timeout to 1 hour , to support slow startup and be debugger friendly . 
Fixed bug in shell script found by Rajeev B . 
05160d7 189bbd9 
Record 
Remove wrapper version check assert . 
f66bdfc 2d437d0 
Add changes entry for COPY TO fix 
Add Eclipse . 
more documentation on API 
Add back setDivider ( null ) , setDividerHeight ( 0 ) 
Changed rid in RequestDeleteMessage from required to repeated 
LPS - 43802 - tests 
ignore Update ' modules / apps / collaboration / comment / . 
ignore Update ' modules / apps / foundation / plugins - admin / . 
make gradlew executable , also test with Java7 
Add missing library to linker command line . 
7e82b9995 7ee22537e 
Added Devaraj Das as a contributor of HADOOP - 6888 . 
 @ JsonObject classes may be non - public 
Release 0 . 3 . 1 
release 1 . 1 . 6 
Updating Alloy 
ignore Update ' modules / apps / web - experience / site / . 
ignore Update ' modules / apps / sync / . 
MinecraftForge / FML @ dc02d56195606d3ba2f1c5036fc8c0ddb67c843f Fix derp with ModType annotation . 
ignore Update ' modules / apps / foundation / hello - soy / . 
added IP address into sandbox file name 
Bump aeson upperbound 
images for installing under Ubuntu 
LPS - 63408 Adds new category highlighted for portlets 
Update to latest Hector 
Added a MOTD 
Increate the max memory for javadoc 
disable unit test 
Switch to full gradle version 
fix build 
ignore Update ' modules / apps / foundation / portal - security / . 
update bundled JRE to 6u39 , refs OF - 612 
Added tag 0 . 2 for changeset aa491af82d9a 
LPS - 52139 make sure to cleanup template managers 
fix javadoc 
Add image for new avd 
Updated gitignore to ignore hprof files 
Update the version to 1 . 3 . 0 
Updated to FML build # 142 , fixed FML compilation issue causing missing files when reobfing . 
add tomee build leftovers to . 
Run full build on Travis CI install 
clean action in script misses target folder for android 
b5d9176 fce776c 
Update AlloyUI to de0c65 , LPS - 32285 
New app icon for beta build 
multi - line layout in TOC 
Added junit version . 
Latest spring - binding . 
Back to commons - collection 3 . 2 . 1 
3f701c5bb e8af3821a 
Record 
Update 
Fixing build . 
Git - ignore a couple of neo4j - home directories that are created during build 
3266f60 60e1dc2 
stubborn stubs 
typo 
Upgrade to Apache Commons Codec 1 . 10 
Record 
Updated changelog 
 ' 0 . 13 . 5 ' . 
Prepare next development version . 
b3e950a dc538f4 
Add parent to prepare build 
Defined relateivePath to avoid Maven warning ( see MNG - 4687 for more info ) 
cb629f3 6a79777 
Todo updated and BitDeli badge added 
update readme 
fix 
e4bb497 a577f5c 
LPS - 58383 rollback 
LPS - 60633 ( WEB ) Move java Files 
Adding more info to api diff report 
The ICU data is no longer compiled directly into the shared library . 
Upgrade to Mockito 2 . 0 . 82 - beta 
Fixed zeroClipboard . min . js 
Update sdk and build tools versions 
Uses default value if setting has wrong value for video max bandwidth . 
added todo 
Prepare next development version . 
Rebuilds libAEGetURLEventHandlerAgent . jnilib for Mac OS X 10 . 4 compatibility . 
workaround to ensure correct getpass ( ) operation in Django manage . py ( PY - 386 ) 
CORE - 2139 H2Database . supportsDropTableCascadeConstraints ( ) returns false 
Added get point method to Line3D . java 
Record 
Add barchart wiki image 
Fixing broken dropdown asset 
great , hudson works . 
update DemoOfUI . apk 
Small fixes 
3ed8dcf 364e92d 
Try a different travis config 
Update maven - shade - plugin to 2 . 3 
Updated for weekly release 
beae34a 1d87bd7 
j 
cfe16be 3d4beb5 
ignore pdf . jar 
LPS - 29482 Source formatting 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
fixed icon 
LPS - 14939 Source formatting 
2f374eb 8180ca8 
fix name 
version bump to 1 . 4 . 0 - alpha3 
change 
Fixed typo for NETHER_WARTS 
gson v2 + 
LPS - 31063 XSS vulnerability with swfuploader 
Add moon point 
Should have been in last commit . 
ignore Update ' modules / apps / web - experience / asset / . 
added svnclientadapter . jar to copied jars in the distro 
ignore Update ' modules / apps / foundation / portal - configuration / . 
fix task re - scheduling 
delete batch config file in quickstart 
Removed pre - built binary from sample . 
Set the indent style for Emacs users . 
fb221b9 2c578db 
fix # 1249 
 ' 1 . 3 . 10 - SNAPSHOT ' . 
Fixed bug with BlockFlow . equals 
Added STORM - 1873 to Changelog 
Added STORM - 1011 to CHANGELOG . 
LPS - 42755 The reminder box are different in template 
Update PatternTest . java 
Use apt addon 
Fix mislabeling issue 
Don ' t wrap message attribute headers 
Prepare for 2 . 4 . 2 release . 
toString fixed in Call 
Use older version of yammer to be compatible with skeleton 
Update qa - controller . 
varargs resolve bug 
Update to discovery - server 1 . 21 
LPS - 10945 Source formatting 
Update ecj . jar 
make sure JSON files are ignores in resources / 
Fix the missing break statement . 
be4c009 520e5e8 
Move leanback gradle build to java 1 . 7 
ignore Update ' modules / apps / foundation / frontend - js / . 
update to using jmh 1 . 13 
Add Oracle JDK8 and OpenJDK 7 
Whitespace police 
Fix 3082859 - missing mdpi text handle assets 
Reduces log information about harvesting time . 
Updated ognl to 3 . 1 
PopupFactoryImpl $ ActionPopupStep . hasSubstep 
 ( no message ) 
ignore Update ' modules / apps / marketplace / . 
Iron python test fix 
simple chunk patterns 
Added splash screen for linux 
Add adapter for CraftBukkit 1 . 11 
Update first run backgrounds with new logo , add xhdpi version . 
Update README . md 
a0140f5f0 658d38803 
Unused import . 
add bin / and gen / to ignore list 
9e076a6 184df10 
update dict 
edf4917 167ddb6 
b6a6791 952211b 
bc49b43 59962ce 
59ff85a 2000fe5 
Update readme for CMD 
ebe9ac8 6baa88d 
Add __init__ file to artificialproject package 
Removed mockito all references from NOTICE file 
Fixed a compile error in example view holder code 
copy for tag roboguice - 2 . 0 - ignoreme2 
removed unused property 
Add hint about timeout setting for REST client 
added singleton class diagram 
 ' 1 . 1 . 104 - SNAPSHOT ' . 
fix build - - use named object instead of instance of Any because Any not mapped yet in JS backend . 
oops typos 
prepare for next development iteration 
Updated TCK . 
LPS - 64991 Include Ant plugins as Gradle projects 
another change related to tomcat kill switch 
LPS - 10247 Source formatting 
Added comment to explain change in Travis build script . 
remove identity_udf . jar from source ( Vaibhav Gumashta reviewed by Thejas Nair ) 
New version 
LPS - 68979 Do not skip task on empty sources 
59d1b79 eb7748c 
Adds Throwable - less Exception 
updated . 
Update SpongeCommon for UserDiscoverer fix 
removed System . exit ( 0 ) from RunTests 
Fixed a naming issue 
Clear results of SCI scan on reload 
Changed dependencies to milestone versions in preparation of tagging 
Do not include svg - s in the default resource pack 
931d1da be09298 
Fix SOE . 
c1e66383d3 ce5229098c 
added plugins in gitignore 
coverage - agent is also needed on the classpath 
added missing hibernate commons annotations jar 
5cd060a 1c68853 
ignore Update ' modules / apps / foundation / portal / . 
LPS - 58746 sdk 
Added the HL7 DataFormat to the jaxb index 
LPS - 22559 Source formatting 
50ea942 ab5d66a 
632bc63b5 bac9b7bfb 
7a7c95e 54bb575 
Improve dist . sh script 
updated changelog for 0 . 9 . 5 
Rewind buffer before copying into it . 
Fixed test data 
JAL - 54 Add licenses 
Missing from the original commit for GRAILS - 2853 . 
clear callbacks when restart websocket session 
Upgrade to ByteBuddy 1 . 4 . 25 . 
Updated changelog 
Fix the path to TestStatsRpc in the makefile 
 ' 0 . 6 . 1 - SNAPSHOT ' . 
e626f3d 446e086 
Fixed get asciidoc missing section warning 
00c6d8bff 769b3412c 
use Array . clone instead of Arrays . copyOf , to be compliant with java 5 
Add cast to EditText to avoid compilation error in README 
Fix returning wrong field 
ignore Update ' modules / apps / collaboration / microblogs / . 
copy for tag roboguice - 1 . 1 
Delete libbulletjme64 . so from samples folder ( why is it there anyway ? ) 
 / / nutz . googlecode . com / svn / trunk @ 1014 423f10f2 - e3a4 - 11dd - a6ea - a32d6b26a33d 
update for r2060 
Updated sample with new basic dialog with long scrollable content for release 0 . 0 . 6 
ec1f8f9 23b957c 
Upgrade gecko to 1 . 1 . 4 
fix MockVirtualFileManager compilation 
added . 
LRQA - 28383 Add Modules Unit as a component 
Fixed text . 
Update SpongeCommon for command cause fix . 
change from ucla - > berk cran mirror 
trival fix to make hash code positive ; patched by Joel Koshy ; reviewed by Jun Rao 
ignore Update ' modules / apps / collaboration / blogs / . 
disable a doc comment 
Travis CI does not provide oraclejdk6 
LEP - 4792 
Mac 32bit . 
Update ' modules / apps / foundation / roles / . 
Update CHANGELOG . md 
Create README . md 
516c68ce ada7f782 
Increase sleep from 2 to 3 because h2o itself does a sleep 2 on the REST API 
ignore Update ' modules / apps / marketplace / . 
ignore Update ' modules / apps / collaboration / invitation / . 
Updated gitignore to ignore DS_Store files and lib / ivy . 
get the date right 
Inflate my ego ( add Aphoh to the contributors list in README . md 
Specify jar name . 
Update SpongeCommon for command chunk load fix . 
update sample properties 
gitignore 
ignore Update ' modules / apps / marketplace / . 
ignore Update ' modules / apps / foundation / portal - security / . 
Shorten control showing phase 
Update colors . xml 
27eb205 986b46d 
remove temp file 
Updates libjitsi . jar with a clean one , as the one committed in r10347 is broken 
Added screeenshot of the sample app for IgnitionLocation 
7931100a e9c7fbd6 
Updated architecture diagram 
Update README . md 
dae448b e561296 
fix com . alibaba . druid . sql . parser . CommentTest . test2 ( ) failed 
LRQA - 25026 prep next 
Update metaServer . sh 
LPS - 56836 SF 
remove not used bottom partial 
remove useless semicolon 
changes for 1 . 5 . 1 
Remove unused import 
Remove unused import 
Deprecate getAssociatedNode 
Travis CI config , to ignore Maven branch 
Add . 
The master branch is actually compiled against the optimized reference branch 
Deleted 2 lines too many in previous commit 
Added my name to the contributors list 
969964a2a cd2238d3e 
ignore Update ' modules / apps / web - experience / journal / . 
244d18b 99689a6 
Test commit . 
adding branch in . 
Destroy console silently on close . 
Fixed remove webiew bug 
ignore Update ' modules / apps / collaboration / item - selector / . 
Add . 
updated changelog 
LPS - 37474 
upgrade parent pom version 
d73e66c 06c2315 
17302a1549 b83c1e3f01 
Remove samples from main POM 
Missing space 
possible fix for # 149 and # 142 
 ' 0 . 15 . 2 - SNAPSHOT ' . 
LPS - 54457 SF 
Replacing all data files with internal references with new ones . 
ignore Update ' modules / apps / collaboration / microblogs / . 
increase sleep for R CMD check shutdown example 
make sbt executable 
Cleanup imports 
81f7b3e a3ce1db 
Source formatting 
unbalanced parenthesis . 
ApplicationImpl . b 
Preview of decor example 
fix example 
422f4ef 6084001 
Made hashCode ( ) safer 
ee97fb6 4868943 
Add empty < application / > tag to fix # 12 . 
Change minsdkversion to 10 . 
adding jdk8 to travis build 
Update SpongeCommon for text config serializer fix 
Add adb devices to circle . yml 
Flush binder buffer after setting raw heap to avoid leaking a reference . 
fix problem with binaries 
javasvn updated ( 1 . 1 . 0 . 
Upgraded parent declaration in all trunks to use version 1 of parent - central . 
Remove unneeded stuff . 
fixed the build 
fbd1736 d75a0c6 
tmp disabled balloon hints 
c961de9da b3eeef39e 
Updated refs 
Updated version in README Maven example 
Sync 
464ce4af4 a538b3ad2 
Update Shadow plugin . 
Push version to 190 . 
Fix layout 
Fixing opcode reset during PAYLOAD 
8d25eab f1aa297 
fixed 
switch release profile to eclipse - release which should pick up aggregate on next release 
add empty header placeholder 
what the actual fuck 
ignored a few more IDEA files 
7b099afb bb5476f6 
optimize 
ignore Update ' modules / apps / collaboration / image - uploader / . 
a749324 7863eb1 
Attempt to eliminate flakiness of DaemonLifecycleSpec . 
Bump common to really fix # 692 . 
Correct method name in log message 
Update time zone data to 2015e . 
fix dashboard # NO_ISSUE 
Upgrade to SupportLib 23 . 4 . 0 
Replaced huge screenshot 
Have a nice stacktrace ! 
update build tools 
NinePatch , added getTexture ( ) . 
ignores for git . 
 / / github . com / antlr / antlr4 / pull / 875 to java runtime Parser 
Corrects exception when rapid succession of RTP DTMFs are sent . 
Update bower . json 
Retire librslib_rt . 
Mark CanvasRenderingContext2D . prototype . canvas as non - nullable 
Implement PrestoConnection . getTransactionIsolation 
Update travis configuration to use latest SDK 
Updated help file 
Update README . md 
ignore Update ' modules / apps / web - experience / product - navigation / . 
ZOOKEEPER - 383 . 
update jar 
javadoc 
Fix . 
Use tests . jvms = 1 like the old parallelism of 1 
Comment on NPE fix 
Add the xxxhdpi icon file 
Update ' modules / apps / foundation / frontend - editor / . 
Update README . md 
Update . 
LPS - 51894 Broken DB generation with too small initial counter value 
LPS - 68131 sdk 
Update reference to library 
Force gradlew ( and other shell scripts ) to use lf line endings . 
464b225 efb8eda 
Fix for failing windows build 
Update version to 1 . 4 to prepare release 
typo 
Delete . 
Prepare version 23 - beta3 . 
LPS - 39158 - Source formatting 
update 
Enable Travis 
LPS - 67863 journal - content - web packageinfo 
H2O on Hadoop - HowStuffWorks Version 
Released version 0 . 5 . 
revert 
update location module 
Update README . md 
LRQA - 15488 sdk 
Use the new Maven central repository url 
 ' 1 . 1 . 114 - SNAPSHOT ' . 
Increase version code 
avoid hanging builds when downloading cache archives 
Fix there is no @ drawable / ic_next Bug 
 / / nutz . googlecode . com / svn / trunk @ 745 423f10f2 - e3a4 - 11dd - a6ea - a32d6b26a33d 
completion invoked in empty autopopup phase = second 
eadef362b 75984848a 
dad21639d 8acc18db4 
Changed javax . servlet - api dependency scope to test 
7837294 85d6f29 
Fix calling startConfirmation instead of startCommand . 
Added app icon for xhdpi 
2d54227 604d6d2 
Fixed a code typo 
 ' rxjava - 0 . 11 . 0 ' . 
Prepare for next development version . 
Unnecessary entry ( duplicate ) 
Translated using Weblate ( Danish ) 
fix wrong name 
Improve Readme 
ignore Update ' modules / apps / foundation / configuration - admin / . 
The GroovyClassLoaderTest actually modifies the source encoding value of CompilerConfiguration . DEFAULT ( and doesn ' t reset it ) . 
Enable VBO on iOS 
fc8ae40 31a0b95 
Update the Bazaar ignore list to include the Gradle build ephemeral directories . 
Allow restore from any AntennaPod version 
prepare for next development iteration 
Built the latest snapshot 
Delete ic_launcher . 
cc24885 4e2a67d 
Change version to 0 . 2 . 2 snapshot 
fdafa590f 6964f69ac 
Remove unknown topology . acker . tasks config 
Bump version to 0 . 3 . 0 . 
Fix Groovy - 226 . 
a short test list that ' s failing with port issues 
fire texture 
should not allow setting of the world 
hack to let appveyor cache maven repo 
rebuild of mac native code . 
added more gremlin pictures . 
Doubles the height of chunks ( once again ) . 
moved to the directory matching the declared package 
Removed spurious break . 
Configure checkstyle maven plugin to validate only ' src ' folder 
ignore Update ' modules / apps / foundation / portal - template / . 
Bump common to Fix # 959 . 
Make getByName actually return values . 
fix travis4 
Run rmtypedefs on framework . jar . 
eee2c72 d75932b 
Pass in platform argument in offline building 
Update dmg window size and icons position . 
Add new apk . 
use const char in 
c58c61b dc210ad 
get rid of useless comment 
Prepare next dev iteration 
22ae5d6 8e7c1b1 
Guard against an empty clipboard . 
update Readme 
update idea CE ico 
Strip " Random seed " printline from TestAggregators 
ignore Update ' modules / apps / collaboration / document - library / . 
remove unused lib 
5473ffb a934ad1 
released 
version 
Make sure JRuby has ( the latest ) bundler . 
Upgrade to Flow 0 . 4 . 49 
set cam quality to 100 . 
ignore Update ' modules / apps / collaboration / blogs / . 
accept android sdk licenses on travisci 
 update apache jsp to 8 . 0 . 27 
add screenshots 
Fixing crash in ViewGroup . dispatchPopulateAccessibilityEvent 
Adding video link 
update lib / quava - r05 . jar from maven central 
Revert " Updated netty version . " 
LPS - 51081 Use local jars as dependencies for the ThumbnailBuilder 
assert title in notification 
prepare for next development iteration 
update version in build . gradle 
fix failing test 
Update Travis to new infrastructure 
LPS - 34324 SF 
update connection icon 
update read me with gravity 
CHANGES update for last commit 
Fix start - mac . 
updated es module 
Sync 
add # 4150 to CHANGES 
Added a protected method to retrieve the indent printer for reuse in subclasses of MarkupBuilder 
update support libraries 
Set version of gpg plugin . 
Update pipe contents localization 
 ' 2 . 0 - RC10 ' . 
modify pom version 
update NEWS 
LPS - 17441 Visual formatting 
Record 
make stress executable 
update BasicGameProject zip file 
Fix text size in movie details . 
Corrected mis - named layout folder 
e57c6c8 0aea293 
Sync 
proposed bug fix 
LRQA - 26644 prep next , use latst 
Tweak code sample 
add Chinese Language Changes 
LPS - 9306 Source formatting 
Added roboto font ttf to assests folder 
Don ' t specify android . jar or lib folder location . 
update version so 4 . 5 . 1 tests / builds 
Forgot to add . 
remove clearing storage 
aa428a2 abf82f9 
DO NOT MERGE . 
add missing words 
fix jitpack reference 
Don ' t link librt on Mac 
Require API 9 + due to MotionEvent . PointerCoords ( ) . 
3a70cf3 5a77371 
7a0d746 a8313e7 
Fix id10t debugging . 
LPS - 61952 git - commit - plugins 
Updated JavaApplicationStub , which runs both on Leopard and Tiger . 
LPS - 26408 - Icon for closing message is not working in Message component in IE < 8 
open class 
f1ec91f a2c10ca 
events with no message are only generated by fireFileFinished , 
Update core - traits . 
Remove log line from ConfigurationBundlePreview 
Added ' log ' back to windows cli tooling 
Font chooser added 
remove local that was masking the superclass field 
Record 
b60a658 8af305f 
Sync 
up version to 0 . 1 . 65 
Bump for 4 . 0 . 1 hotfix . 
Remove old images 
Bring api and facebook projects in line with our core build target 
Create a Git ignore file . 
update test data for SerializationsTest 
travis build check 
Corrects typo of a test name 
fix for cross - domain request in IE8 / 9 not using XDomainRequest for push ( ) 
Test Fixes - portal / controlpanel / calendar 
cebf055 b6b233b 
add some words 
ignore Update ' modules / apps / web - experience / staging / . 
8ed480517 d51253011 
41560f32 373afcd3 
addition of newline to SessionConsole . R 
GRVY - 945 test 
Upgrade to Flow 0 . 4 . 36 
LPS - 61786 Use the first one and break 
Update README . md 
add a virtual destructor to region_rasterizer , to be on the safe side 
Ensure last is re - assigned during unwrapping to prevent an infinite loop . 
version of fastr 
15b4778 a6e5494 
Changed retention to ' binary ' for LowPriorityInOverloadResolution 
remove import 
Update the Git ignore list to remove Emacs backup files . 
updated distribution . xml to include whirr recipes and configuration files . 
goose ( on splash ) comes back 
Add IntelliJ and Mac OS X files to gitignore 
Use Balanced line breaker instead of HighQuality . 
update compileSdkVersion to 23 and buildToolsVersion to 23 . 0 . 1 
Upgrade to remote control 0 . 7 final . 
 / / issues . apache . org / bugzilla / show_bug . cgi ? id = 48582 
configured functional tests to run with forked jvm per - test , possibly hiding a memory leak problem with tests 
5506fbf0 b931b084 
upgraded to latest build with jochen ' s scoping changes 
Remove Tween externs . 
updated splash 
Fix hystrix - contrib submodule path 
da98fbc e736870 
ignore Update ' modules / apps / foundation / server / . 
Update the ( second ) flattr link in README . md 
unused action code has been removed 
6d33f25 079d474 
bfe5d9153 45a7a92f6 
skip maven - invoker in ' dependencies ' stage 
LPS - 51909 Prevent NPE when PDC doesn ' t exist 
added travis config 
ca46b75 e76970d 
Removed build reference to spring - struts module 
tiny dock fix 
Updated version in README . 
23ae083 380c8dc 
Version set to 0 . 2 . 
Use reactive conditionals to hide the button , no longer need CSS 
added titan and captheorem image for documentation . 
cb00f48f6c 2a49e0d96d 
ignore Update ' modules / apps / web - experience / site / . 
BuildSettings wasn ' t handling in - place plugins reliably when checking 
Updated servlet jar to latest version 
Update CHANGES . txt 
0fa4721 98ae02c 
LEP - 1868 
parent value in constructor was backwards 
923585e d6793c3 
updated studio with color and batch script 
ignore Update ' modules / apps / web - experience / export - import / . 
setting version to 1 . 0 . 60 - SNAPSHOT 
dcf89bf 81e609d 
Sonar 
LPS - 61001 Move css file 
Crash when modifying text while using drag accelerator . 
Updated README to provide info about which ADT to use for building . 
cleaned up code 
Update release - notes . 
Do not send flush packet if explicit is false 
bdd6aab 4221d7e 
LPS - 66282 Clear out the map , just in case somehow the test is invoked twice in the same jvm . 
Changed signature of ODatabaseThreadLocalFactory due to obvious implementation name problems . 
LPS - 67499 module - moves inactive . html into module 
Upgrade to Gradle 2 final 
travis pls 
TraversalRequirements now uses canTraverse 
Initial 
3d0820c 6464bfb 
Not released yet . 
Upgraded Lucene version in the docs ( used in links ) . 
LPS - 52826 sdk missing gradle wrapper 
properties 
Update version . 
added missing status messages after message scroll 
initial integration 
Smaller screenshots 
4d72454 4ba9e68 
259a040 43517fe 
Add to git ignore for example 
ignore Update ' modules / apps / collaboration / document - library / . 
Updated example to use parseClaimsJws to reflect most common use case 
LRQA - 22969 prep next 
GRAILS - 4759 - updated ehcache to 1 . 6 . 1 
Update ChapQ1 . 5 . 
Updated travis to only test using JDK 8 
Increased required Android version for location module . 
 / / github . com / jawi / JPty / issues / 1 ) . 
Stop the init script from returning 1 
LPS - 44631 - Source formatting 
add marker interface for station edges 
OK - try this - god I hate Maven 
LPS - 65481 Fix unit test 
Fix error when opening / restoring documents that start with a blank line 
Use same npm version on travis and build_release . 
rename drawable - mdpi to drawable for Android 1 . 5 compatibility 
update changes 
873a39c 0d9e45a 
LPS - 66733 jar 
LPS - 45419 SF 
Run GSP tests in parallel 
LPS - 64350 
exit properly when not able to connect to server 
whoops , removing local shell script 
Fixes a problem with the VP8 Packetizer sometimes not sending the last chunk of a packet correctly . 
Update to Flow 0 . 2 . 22 
majorVersion 2 . 21 
export META - INF so that aop . xml is visible to aspectj load time weaving in an OSGi environment 
ignore Update ' modules / apps / marketplace / . 
Log full test exceptions . 
description of svm_scale . 
removed roles from neo4j recipe , since they can not be part of a recipe 
ignore Update ' modules / apps / foundation / frontend - js / . 
update dep version 
release 2 . 1 . 0 
upgraded to ES 0 . 90 . 7 
hide feedback button in mobile view 
Update icons 
forced the SEED to be a constant to match failing jenkins 
962d450 3e094bd 
Fix msn log in . 
b489ca93d 8625448de 
0c69a3e 8ffc231 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
Prepare version 27 - beta3 . 
vertical alignment of cells in class . 
Update the mdpi resource with 2 . 0 style icons 
Clean - up post init / destroy lifecycle refactoring 
CAMEL - 2185 reverted my last commit which can ' t do what I expect and caused camel - cxf build error 
Updating Alloy to 47f0c31 ; LPS - 29614 
Updating Alloy 
LPS - 15480 Update alloy - taglib . 
same as ANT = > no ' Use ' pages in javadoc 
setting version to 1 . 0 . 140 
Update TODO . md 
Fix steps number count 
Update README . md 
update osx natives 
6d25bd347 b6b67816d 
Fix to nav , added _book . yaml 
fixed # 70 # 65 
fix blinking test 
black and white 
d2e2159 4a577bf 
Added scope test to OkHttp Client 3 dependency 
fix warning 
LPS - 63865 rename sample file in css - builder 
Shortened collection converter example . 
ignore Update ' modules / apps / collaboration / blogs / . 
remove osx 
Updates libjitsi to a version which uses a 2 - channel format 
Update README . md 
no_reply @ jetbrains . com < Igor Kuralenok > 
 ' astyanax - 1 . 56 . 36 - SNAPSHOT ' . 
Update SpongeCommon ref . 
use fastjson 
Update to Flow 0 . 2 . 26 
Sync 
Missing key 
More travis tweaking 
Update SpongeCommon for block decay fix . 
Ensure StatHat is not stripped , re # 370 
fix ticket number in CHANGES 
move org . codehaus . groovy . grails . validation . Validateable to the grails - plugin - validation sub project 
Speed up consistent hash ring 
Update to new calimero version with support for 3 - byte RGB data type 
LPS - 54611 sdk 
new dimen for set spacing 
fix issue of icons not being themed when setting it on a ` TextView ` 
when a key is hold down on Windows , it generates several start DTMF events and only one stop when released . 
5624b30 36425d1 
prepare 0 . 17 . 1 release 
Fix reading sleep policy 
Support 23 . 2 . 1 ( 2 ) 
bump version 
make example snippet in release notes clearer 
Updates the jain - sip libs to match the versions on the web site ( ver 1 . 0 . 96 ) . 
update 
 ' RELEASE - 0 . 1 . 13 - SNAPSHOT ' . 
change jar package 
Revert " LRQA - 25160 1 . 0 . 40 never seemed to exist " 
6ed0a43 746b380 
Remove debugging line 
1 . 1 . 1 - SNAPSHOT 
 ' curator - 1 . 3 . 4 ' . 
LPS - 53893 sdk 
f7bfacd 60fb850 
make - maven - plugin 
trying to be smarter about setting a default timezone when one isn ' t found 
8968e951d 9e5e3c5f3 
Added the maven - smali - plugin and smali - integration - tests modules to the parent pom 
don ' t upload empty jars to maven from sdk project 
removed more manifset files 
Update library reference 
Mark callable reference candidate as error when there is error type . 
get aggregate back into release 
update darwin natives 
LPS - 36001 SF 
Update preview 
Update readme 
8459a01a61 50f111d177 
Make NavigationView scrollbar visible 
TestApp no longer overrides ' grails . env ' setting - fixes GRAILS - 1988 . 
update splash . png 
Adding Eclipse - related files to gitignore . 
deleted release 
LPS - 49129 - dependencies 
fucking manifest 
LPS - 66316 ( SERVICE ) Move service xml 
LPS - 13513 Hudson does not compile anyway 
d691056 36425d1 
bump engine . io - client 
ignore Update ' modules / apps / web - experience / asset / . 
0617be6 1ee0cc4 
help ID ( PY - 4107 ) 
Fixes java 1 . 5 error . 
added xml version to theme . xml 
Clean up 
LPS - 22625 Rollback . 
LPS - 52139 not needed 
use base 3 . 1 . 11 
ignore Update ' modules / apps / foundation / xstream / . 
release 2 . 3 . 6 
Smack 4 . 1 . 0 - beta1 
Added a @ since tag to the javadoc 
updated from trunk 
Fix checkboxes for message_list_item_touchable . 
increased memory allocation 
ignore login - web 1 . 0 . 7 prep next 
Added readme . txt under sevrer / plugins directory 
remove relevant words from ignore - list 
Adding newline 
Create README . md 
Delete ic_launcher . 
Add deskshare object to meetings 
ignore Update ' modules / apps / web - experience / asset / . 
Changed body to be required in update_aliases 
Bump to newest revision . 
0b6913e 45955e6 
ignore Update ' modules / apps / web - experience / product - navigation / . 
Add note to include ' java . io . tmpdir ' in the set of immutable system properties 
 / / github . com / cgoncas / arquillian - extension - liferay / pull / 11 
update to 6 . 11 - SNAPSHOT 
release date 
remove info 
Compile tests with source attribute . 
cleanup formatting of file 
b4d06e2 8f7bd1f 
Prepare for 0 . 8 . 2 release 
c07d24f f3cb49b 
Update README . md 
1088469 ade631e 
Simplify the definition of __inline 
Revert " LPS - 44610 Update Alloy taglib jar ( Alloy " 
missed increment of i 
5e87bf33e a63ff4bf7 
update docs 
Prepare next release v0 . 85 . 2 - SNAPSHOT 
triggering once again 
419dcb38e c3b12c917 
Allow TERM to be set to xterm - 256color 
Better ignore file 
updated images for tutorial 
Fix a bug disappearing installerPackageName info of packages after reboot . 
Increased version 
compilation fix 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
cleanup 
Removing ( char ) - 1 cast from the test 
Version code updated 
Fixup for 5fa7e65816 ( forgot hdpi drawable ) 
1080 * x - > 600 * x 
Updated TCK . 
Preparing for release 0 . 4 . 0 
version changes header for rc1 
fdb71b6 ffc758d 
new item 
Regenerate Kotlin bindings 
Fixed a regression in AuthenticatingConnection on checking for isClosed ( ) . 
Update SpongeCommon for timings version export fix . 
Record 
Use git protocol instead of https for submodule references - - avoids Windows msysgit flakiness 
MinecraftForge / FML @ 704a70902fca3de620375116a33dccd3d6d576d0 Sanitize input to isRemappedClass to use ' / ' as a package seperator like the srg files . 
Added version properties file to be ignored by git 
s / MySql / metadata storage ' 
Update README . md 
JB dictionary extended 
daedcc4 1f6ac8b 
Add missing description . 
Undo wiki images 
add gitignore 
Move the heroku env config out of the procfile . 
test fix 
fixed reloading TestModuleProperties after reopening ( IDEA - 150835 ) 
Update changelog 
Update ' modules / apps / web - experience / layout / . 
Add Gitter webhook as a secure Travis key 
fix example path of android - ndk 
updates changelog 
Update README . md 
ignore Update ' modules / apps / web - experience / asset / . 
Revert " Update . 
Record 
forgot syslog4j step in travis 
PacProcessor should be 32 bit only . 
Fixed Markdown typo 
Wrong end test function 
Bump jxmpp to 0 . 5 . 0 - alpha7 
Moving Java sources to source dir . 
be01800 1aadfc2 
LPS - 65757 Document that Parallel Rendering is not available in the current version 
3a79e43 0ad58de 
Document the version of protovis 
Using latest neo version . 
Update jportaudio JNI for FreeBSD ( 32 - bit and 64 - bit ) . 
Force JavaDoc to intepret code as UTF - 8 
Updated changelog 
Record 
Comment out updateOrInstall since that broke jenkins build . 
don ' t use eap candidate 
 ' 0 . 6 . 7 - SNAPSHOT ' . 
update changelog for STORM - 210 
Updating Alloy to 6a86501 ; LPS - 15633 
0bc3607 7816859 
bump version 
Fixes build . 
Added files via upload 
Add custom script to Travis 
Create README . md 
ignore Update ' modules / apps / foundation / portal - settings / . 
added changelog entry for package change 
woups 
Update list widget preview image . 
ignore Update ' modules / apps / foundation / portal - search / . 
Upgrade to RabbitMQ AMQP client 3 . 6 . 2 
Change max heap size to 48MB 
fix query / wait emitted twice 
eclipse autocompletion is gonna kill me 
Added IF to prevent NPE 
help ID ( PY - 4116 ) 
Fix config 
Update CONTRIBUTING . md 
06ad393 77f55c5 
Screenshot 
updated PDF 
execroot_test 
eb2e139 a0cbcd5 
44c3095 935dedf 
copy language properties from plugin 
9d9953d9 5c43f73 
yota branch has gone 
Remove the divider in Upcoming and Recent lists . 
Update doc commit pointer 
Source formatting 
ignore Update ' modules / apps / foundation / portal - security / . 
Commit test to see if BJ notices CVS changes 
IDEADEV - 9634 
Now mSupportMultiTouch is depending on WebSettings , 
bump version 
updated ChangeLog 
validate numericality of port 
Avoided building tags , this way we avoid building a commit twice . 
Revert " LPS - 49233 " 
Update README . md 
CPP - added Chap1 problems ( 3 , 4 , 5 , 6 , 7 , 8 , 9 ) 
d84d289f 0f20710 
Not yet for socket . io support 
6ce0a07 3877089 
Ensured the next version can be published . 
update kotlin to 1 . 0 . 1 
Upgrade to version 1 . 6 . 1 ( was 1 . 5 ) 
snapshot 
update es / upstream to remove obsolete test 
Upgrade maven - surefire - plugin . 
Don ' t fail on extra translations 
Fixed findbugs issue 
45b1e5e 4898892 
New Development Version 
8e90f42 13b4eed 
b192ce47 91c54e3e 
Revert " gitignore " 
2932e72 9566990 
Record 
Adding idea support for the less fortunate ones 
ignore Update ' modules / apps / collaboration / announcements / . 
common jvm args for community 
add findbugs exclude - > thrift dto 
f2c3dc410 41d2c05ff 
removed a line for external testing , tic 232 
Added STORM - 1250 to CHANGELOG . 
Whitespace police . 
add pygobject 
LPS - 25058 Source formatting 
ignore Update ' modules / apps / web - experience / asset / . 
Add flowdock notification to Travis build . 
LPS - 48388 SF 
Add OSX build 
Record 
56b184e 250c617 
Update SpongeCommon 
Excludes scala dependencies from zipkin - cassandra - core 
Write checkstyle to stdout . 
f83d7785 f3ab3c3 
Some general improvements and additional tests . 
ignore Update ' modules / apps / collaboration / announcements / . 
LPS - 66316 Disable for now 
updated version name / code 
update jar 
Add missing @ Override annotation 
Need Java 1 . 7 for Heroku web app . 
new deskshare jar with sending message to stop sharing 
JvmMetricPoller ( ) should be public 
ccfcd9e 6ab77bd 
a6ca41793 86d67c301 
update CHANGES . txt for CASSANDRA - 3081 
Update CHANGES . txt to reflect commit of MR - 6273 to branch - 2 . 6 
added , 
103b560 2b6257c 
update jar 
Hosted MC documentation improvements 
88d109d 56195db 
Release 0 . 3 . 2 
c7c5692 7fdb4eb 
Update README . md 
ignore Update ' modules / apps / web - experience / export - import / . 
Record 
Update README . md 
lucene libs 
1418ec854 5040b8de2 
JSP Parsing Problem ( IDEADEV - 17777 ) 
update to latest support libraries v23 . 3 . 0 
056b131 1ed0e55 
test commit 
Added STORM - 1631 to Changelog 
Websockets now need this method . 
jar v44 
receiver . close ( ) invocation is missed in msreader example 
For new version release . 
Update README . md 
New banner for h2o world . 
upgrade okhttp ( 3 . 3 . 1 - > 3 . 4 . 1 ) 
add STORM - 2070 to CHANGELOG 
Updating Alloy - YUI milestone 3 . 1 
javafx manifest for default project 
Prepare release notes for 4 . 13 
update changelog for STORM - 796 
ignore Update ' modules / apps / foundation / portal - scheduler / . 
avoid reading the whole file 
8dd80c5 53644fb 
and one more commit for the cronjob 
new embedder 
Use admin layout for OAutH provider pages . 
default constructor of Sprite didn ' t set the color . 
A notice to third - party users of this distribution . 
added moco logo 
LPS - 38101 Need to reset on clean up 
c4d7721 fcd7cf2 
LPS - 46227 SF 
Updated example . 
add imgs 
reenables tests 
Remove useless static keyword . 
df030df 790c679 
3f9bd6c 96811c2 
update to latest ` FastAdapter ` v1 . 5 . 0 
Add environment var to make webapp work on jre 
Update ' modules / apps / collaboration / microblogs / . 
LPS - 58108 Use the correct package 
async / await is not part of ES7 
ignore Update ' modules / apps / web - experience / product - navigation / . 
Nothing was done . 
61164f2 c314179 
ignore Update ' modules / apps / web - experience / asset / . 
ignore Update ' modules / apps / collaboration / image - uploader / . 
Update README . md 
Remove deprecated constant 
OC - 13230 Cmd + Shift + K is used for two different options in the default keymap 
moved to the directory matching the declared package 
Use newer sonatype pom . 
Perforce file deletion handling fixed . 
Update 
new verison for new icon 
62243c7 8c56912 
75fdb85 46689e5 
1fe0dcec0 b78868612 
Corrects deadloack between the CoreAudio AudioDeviceStop function and the stream processing callback . 
example OpenOffice . org documents 
CORE - 1970 NullPointerException on rollback with < sqlFile > tag 
b0767c8 22810c4 
LPS - 5240 
Updated changelog 
README 
e3f13a8 c94a20e 
Update Artifactory here too 
13c433f 82768db 
LPS - 64225 Semantic versioning 
Script hcat is overriding HIVE_CONF_DIR variable ( Jarek Jarcec Cecho via Ashutosh Chauhan ) 
e1d6240 8075d7f 
Add lib / html / sax / push_parser . 
Update Version in ReadMe 
test 
Make force protected for sub - class access 
Formatting fix in TachyonFileTest . 
Add SQL Console module to jOOQ - Copy authors . txt 
post release bump 
Update README . md 
Fixed the TitleParserTest to reflect recent updates in behavior 
Remove mavenLocal ( ) from buildSrc 
LEP - 4510 - Themes should contain styling for commonly used elements 
update speedSearchPrompt icons 
235ea3b dcc882e 
LPS - 39457 Unwrap response from reCAPTCHA 
Added gitignore . 
Update changelog 
967d11a1 a6c1522 
Suppresses deprication warning . 
Added missing ndef technology to getTech . 
fix cqlshlib tests 
Missed a PHONEGAP reference 
Record 
Oops 
Use maven - compiler - plugin 2 . 4 
remove . 
add an accessor for the executor service 
Fix typo in typo fix 
d9a6c485 7a3aa7e4 
ee614db2c 8b8afbf16 
ignore Update ' modules / apps / collaboration / blogs / . 
Updated the most recend DLL . 
Also unhide WifiConfiguration . lastUpdatedUid . 
Updated the help file to refer to add - ons instead of plugins . 
 ( GROOVY - 2293 , GROOVY - 2236 ) Update to JLine 0 . 9 . 93 for win64 + delete key habndling 
Add cassandra - topology . 
Translated using Weblate ( Greek ) 
Can ' t have empty sections . 
ignore Update ' modules / apps / web - experience / layout / . 
Ignore fetched JVMLS files 
gradle 
Change revision property in ignition - core 
0a870c7 335805c 
Prepare for next version . 
wrong build tools version 
Updated syntevo SmartGit / Hg icon 
WifiP2pWfdInfo set device type bugfix 
rootdevice " parameter . 
LPS - 41531 Remove unncessary code ? 
Committing Build 
15a87ef af58613 
resize canvas 
Update SpongeCommon for TextStyle negate fix 
Fixes build . 
0006d10 3f57de8 
unscrambled version of ASM 3 . 0 
LPS - 9748 
5cd38bc 3540f1f 
update to latest support libraries v23 . 3 . 0 
rename class to match file 
auto attributes on all text files excepted . 
Ignore really ignores now 
Reduce number of lines printed . 
Skip performance integration tests for the coverage builds . 
LPS - 12499 Add ThreadLocal cache to GroupLocalServiceImpl . getGroup ( ) 
ignore Update ' modules / apps / foundation / portal - instances / . 
fix imports 
Updated example 
Upgrade enforce - victims - rule to 1 . 3 . 1 
257eef3 8afc130 
LPS - 55166 sdk 
Update build tools . 
add missing src 
Fix leak in ZXingWidgetController . 
should fix the RedundantThrowTest 
Forgot to run the complete test set and I had changed a minor issue that cause a test to fail . 
add toolbar to log screen 
Updated pom . template according to sonatype oss repository policy 
Updating to 3 . 0 . 0 - rc1 
ignore Update ' modules / apps / web - experience / layout / . 
conditional import of < PhoneGap / PhoneGapCommand . 
Remove trailing space . 
maven is coming soon 
0491c46 2f80553 
ignore Update ' modules / apps / collaboration / blogs / . 
test audio for the command center 
Added white refresh icon 
Update README . md 
testing instructions 
ignore Update ' modules / apps / web - experience / asset / . 
LRQA - 19127 prep next 
Fixes a dealock in the Windows Audio Session API ( WASAPI ) backend . 
Fixed version 
add the set reference doc to the reference toc 
Update to Gradle 2 . 6 
LPS - 56674 sdk 
Re - add ( dperecated ) addSourceFile ( File ) 
Record 
fix mtk chipset 
Delete unsed mDnsLock . 
Disable proguard optimizations 
6633c38a 92861b69 
Update support library 
Convert NaN to 0 on histograms 
697a43e 2659f22 
add pre no - wrap for markdown 
Renamed test process to make the test run on case sensitive operating systems 
version bump 
ignore Update ' modules / apps / collaboration / comment / . 
adds suffix to debug build package name 
Upgrade to Apache BOM 17 
d639a45 e8101c0 
more working tests - yay ! 
Upgrade to ognl 3 . 1 . 9 
LPS - 57463 not needed 
Make jbosgi - http provided 
ignore Update ' modules / apps / collaboration / bookmarks / . 
AnnotationConfiguration is ignored if the metadata - complete attribute is present in an override descriptor regardless of the value 
Add a ansible doc link in the comment of control_path 
Update gitignore 
adaa5e8513 dae08fea5f 
Release v1 . 0 . 1 
dictionaries improved 
ignore Update ' modules / apps / web - experience / staging / . 
5e75d06 91ac006 
newest groovy jar 
fixed EDU - 263 Python 3 . 2 interpreter cause wrong answer been accepted ( because of exception in import ) 
ignore Update ' modules / apps / static / osgi / . 
Update buildTools version to 22 . 0 . 1 
NEW RELEASE v1 . 1 . 0 - release to maven central 
ignore test db in server 
remove unused field 
update travis build config to pull the newer android build sdk 
Fixed a stray EOL in test file 
Bump common ref 
final slides from rivieradev 
14a302f b61dd3a 
Updated to do 
6fa7bcf 19f5615 
Bug 3293819 . 
7a91fd6 f1b25bd 
ignore Update ' modules / apps / web - experience / layout / . 
f3f80e3 e820825 
23e620b 6ef142a 
2c37b73a5 45011ea81 
74033e9 11c6f8b 
Update to airbase 43 
 / / github . com / morfologik / morfologik - stemming / issues / 14 ) 
add TODO for BIP 
refresh SVN incoming files view together with repository view in background 
report errors 
Updated support libs to 23 . 3 . 0 . 
Check whether WAVE extractor can be initialized successfully in the sniffer for WAVE 
LPS - 55159 Generate 
polishing 
ignore Update ' modules / apps / foundation / portal - cache / . 
refactored stun4j lib 
new packages icon 
Polish 
ignore Update ' modules / apps / foundation / monitoring / . 
Release version 1 . 0 . 9 
New android library plugin name 
4a6ddf5 f59b8f0 
Use new sanitizer option . 
Remove log spam 
Removed border radius on both chat and presentation areas for mobile devices . 
Use Trusty for travis builds since it has a newer JDK 
LPS - 53366 SF 
LPS - 46274 Fix bug 
updated CHANGES . txt for Breton . 
Pass JAVA_OPTS to the grails command to enable it to use a proxy 
cosmetic 
groovy ! 
cde54a039 ce8be4c51 
ignore Update ' modules / apps / web - experience / xsl - content / . 
More for chars . 
reflect the ant - > mvn changes in the gitignore config 
content is converted to a string on set 
LRQA - 26003 md5 . checksum should be a local variable . 
LPS - 66099 Update jar 
Added XEP - 0384 
LPS - 60708 SF 
Remove the unused inclusion of iostream from the JNI code 
added parallel alias 
CPP - 618 Add possibility to run CLion as desktop app on Ubuntu 
Update modules . md 
Updated changelog . 
Fixed wrong filenames for Bintray artifacts 
Add mnemonic to " Force checkout / merge " 
Updated IRC client library irc - api to custom version to test bug fix . 
prepare for 2 . 3 release 
LPS - 24153 Setup Wizard - Don ' t change the original values with the default 
add a disconnect from ANativeWindow 
revised missing icon from paul 
Determinate progress now works as specified in the material guidelines 
TcpIpConnectionManager shutdown scheduler 
Create README . md 
version source and javadoc jars 
remove false alarms that were created by an error in sentence segmentation 
ignore Update ' modules / apps / collaboration / bookmarks / . 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
Made the build messages from the manual less verbose . 
typo in the conf file 
b6a9ebc 43c7aae 
Added Security Interceptor section to index 
Fix a failed find and replace . 
Call WebView # freeMemory before collecting memory information 
Added debug message for job manager shutdown 
LRQA - 21170 prep next 
record working directory changes in activeSession 
don ' t generate icons for IntelliJ laf 
LPS - 10615 - Mobile theme thumbnail 
ignore Update ' modules / apps / foundation / portal - cache / . 
9afbffb 0c58307 
LPS - 41509 Bad dir 
fixed one error with soot on mac . 
ignore Update ' modules / apps / foundation / login / . 
Map KEY_SELECT to DPAD_CENTER . 
287e6c82 d1826f56 
 = instead of = ) 
Descriptor management improved 
wip9 
bd03bc3 da0913b 
Increase the size of some tests that time out on ci . bazel . io 
Version 1 . 4 . 0 . 
LPS - 53819 Edit breaking change , changing " are " to " is " . 
Add EventLog event for logging of attempts to call java . lang . Object . getClass 
clarify the alert documented for " Cookie Slack Detector " to reflect the actual alert raised by that scanner . 
prep 4 . 0 . 0 . 
220b61f ba7e659 
get rid of internal JvmVersion annotation in kotlin - jdbc 
UIViewControllerBasedStatusBarAppearance = NO in SampleApp 
Update common / api for bleeding version update 
Bump common for TickBlockEvent changes . 
Version 1 . 4 . 4 . 
e3aecc0 438238e 
6edac945 a4e383b2 
initial checkin of openhab . yoxos file 
30616759c c9ea0294b 
CPP - 5210 Add " Accessors " to jetbrains dictionary 
LPS - 61952 git - commit - plugins 
2560a4732 14e3a2c70 
9e391d08 1c341517 
a3106d1 2f756cb 
Upgrading to jetty - test - helper 2 . 3 
Git ignore regexes . json 
changed int to double . 
npe when local repository is not set ( ea - 21582 ) 
Delete img 
Use Google Analytics for Android 2 . 0beta4 . 
Deprecate code that is going to be removed 
LPS - 56783 move DDLConstants to api module 
Updated documentation 
db22bdd 87610e5 
LPS - 51533 Run ant format - source 
LPS - 26908 Some unit tests are not working . 
ignore Update ' modules / apps / web - experience / rss / . 
GROOVY - 4075 Fixed the shouldFailWithCause regression . 
Re - enabled test 
Perspective icon fix 
Updates jitsi - videobridge to the latest libjitsi . 
log errors in asyncForwardingServlet 
4176f08a 1c128a14 
Fixed bullet points in README 
Basic overview of SBE 
0d4b4a1 4cd54dd 
LEP - 6298 
Upgraded dependency to android 1 . 6_r2 , because that ' s the latest available 1 . 6 release . 
this time w / o fake retina versions 
Fixes a deadlock in the ICE implementation between Agent . free ( ) and StunClientTransaction observed in Jitsi Videobridge . 
Fix typo 
 ' zuul - 1 . 0 . 25 ' . 
c83f51a41 ed75ab5e5 
Record 
HHH - 8853 - Tomcat jdbc - pool interceptor exception 
Update . 
Add mark at Android SDK Manager Icon 
Changed color for demo . 
c2d9fcd 9719b68 
Update README . md 
Record 
update parent pom to non - snapshot version 
LPS - 48313 
b456a041 5644e28a 
doc updates 
d8092ba 9ba8062 
d8a7893 861f6fe 
upgraded netty to 4 . 0 . 6 
 ' 0 . 7 . 6 ' . 
update applet zip 
Updated changelog 
Source formatting 
Sync 
Add another proposal . 
fixed a small bug 
update native lib to 3 . 2 . 2 
Fix test in eventsArePair ( ) . 
fix windows cmakelists 
Update README . md 
CHANGELOG update . 
alpha - 3 / 245 version bump 
switched version number to 72 
fb40ad0 6e41605 
fix releasing 
Update apk in Google Play 
Add a missing dependency on a shared JNI library 
add A tag ' s cursor css 
LPS - 54505 rename step 1 
Instead of not feeding the AudioTrack any data after EOS , play silence instead . 
LPS - 13906 - Shutdown warning message doesn ' t appear for the users 
Suppress warnings from PsiClassUtil for findModulesWithClass method 
update NEWS 
 / / android - query . googlecode . com / svn / trunk @ 76 d864b24f - c464 - 86f1 - a23f - 96be1521e7f2 
7534e4b 5a00661 
Updated changelog 
voip image 
ignore Update ' modules / apps / web - experience / product - navigation / . 
Another StandardThreadExecutor attribute with " is " 
ab03dfb65 aaa32006a 
EditorToolbar layout fixed 
 ' RELEASE - 0 . 1 . 20 ' . 
missing file 
update win32 - x86 native 
Update to support - v4 21 . 0 . 0 . 
Readded gif 
ignore Update ' modules / apps / web - experience / asset / . 
and again 
Mathias Agopian < > 
rename master . rb to archive . rb 
new item 
Housekeeping - removed TODO 
review comment 
bump the version . 
030a093f4 6d1244c06 
41bce6399 a169538f4 
println removed 
Remove the background from the RelativeLayout , allowing the ActionBar style background to show through 
Ignore a png file that ' s a documentation build artifact . 
Don ' t recycle accessibility event after sending . 
Update changes 
add offset 
Updated date . 
High - res screenshots 
diagnostics fix 
4753b5b 90f13b1 
 / / bigbluebutton . googlecode . com / svn / trunk @ 1789 af16638f - c34d - 0410 - 8cfa - b39d5352b314 
add " jpdl " 
Jabber protocol extensions lib 
9c2ec9abf a5ae18548 
include ' < cxxabi . h > ' ( needed for non - OS X platforms ) 
add jar to libs folder for ant to find . . . 
Removing stupid Mp3s 
push - notifications baseline 
prefer printed output to value 
fixing classpath for the javadoc - compiler 
LPS - 46897 Update the SDK to support it 
3e8b89b 0990511 
Temporary enabling gradle version . 
copyright year - > 2012 
Added STORM - 1959 to changelog 
ignore Update ' modules / apps / foundation / portal / . 
Update README . md 
added a release logo and property files from Gremlin . 
EDU - 296 incomplete test for lesson 2 task 5 
Add Travis config . 
44799284 5a1d97c1 
LPS - 47071 add line break to show the order matters 
Enable OpenCORE on master - part 1 
Corrected test data 
LPS - 66213 Semver 
Bump VERSION to 1 . 6 . 2 . 
Fix release number 
Updated changelog 
Update library reference 
psd resource 
ced6bff 9e218b3 
Source formatting 
8ca48c8 abf4190 
updated help icon 
Add Travis CI config 
Update SpongeCommon 
Fixed integration test 
icon 
additional keywords allowed as property names ( more tests , remove ' this ' and ' super ' ) 
FastArray doesn ' t overwrite toString ( ) method 
ignore Update ' modules / apps / collaboration / blogs / . 
fix simulator build 
fb49772 96e1203 
update support 23 . 2 . 1 
LPS - 67137 Source formatting 
move a missing config file from standalone module 
remove key lookup for account screen ( not a good place ) 
ignore symlinks 
fixed PY - 6248 but PY - 2921 actually still doesn ' t work 
 ' 0 . 15 . 1 - SNAPSHOT ' . 
add changes entry about snapshot functionality 
Add Travis Build 
Bump version post 7 . 0 . 1 tag 
Tweak colors in 2048 example 
ignore Update ' modules / apps / collaboration / social / . 
updated studio 
fastjson - 1 . 2 . 10 
invalidate the webview after pressing the IME ' next ' button 
Add application id to build . gradle 
build fix ; I was confused , sorry 
Update shade - plugin to 2 . 3 
aliasing / to search 
Modify . 
1fcabd7 730c66e 
Added STORM - 295 to changelog 
6322b94 4ea7407 
To English dic 
Update PULL_REQUEST_TEMPLATE . 
GroovyClassDescriptor . getProject ( ) made cheaper 
Prepare next development version . 
setting version to 1 . 0 . 56 
LPS - 26475 Regenerate 
Source formatting 
Remove spaces . 
Update utilities 
b9ee4f4 7f9d9d8 
LPS - 7980 Source formatting 
5b7bd0a 41898f6 
667eeaf 7a8e8f9 
Updated support section 
Adding a travis configuration file 
Build with Gradle 2 . 14 . 
Fixing double declaration of java version 
 ' zuul - 1 . 0 . 7 ' . 
Upgrade to discovery - server 1 . 13 
Update owncloud library reference 
Update ' modules / apps / foundation / frontend - css / . 
Forcing revalidation after entering fullscreen . 
Added STORM - 1719 to CHANGELOG . 
remove old blenderloader . jar 
Use build tools 19 . 0 . 3 . 
Updating Issues list 
add STORM - 1890 to changelog 
Updates libjitsi to a7143beb3 ( fixes a problem with recording ) . 
revise news again 
LPS - 50682 SF 
line needed for connection naming to work 
gh - 58 - changed the travis install script 
7358fe3 62a0222 
Fix missing break in Icon class 
4689b28 d1e323b 
ignore Update ' modules / apps / web - experience / site / . 
added use - idea - classpath 
e986817 c69c8dc 
Add comment to satisfy checkstyle 
 ' 1 . 4 . 12 - SNAPSHOT ' . 
Make sure we also call destroy on AtmosphereServlet 
Update CHANGELOG 
Record 
9a9a5c6d 86285b60 
Try allocating even more heap to the performance test execution JVMs to accommodate builds with much output . 
Update Jetty version to 9 . 2 . 1 . 
upgrade kryo 
next releases are snapshot again 
Upgraded Javadoc Plugin to 2 . 10 . 1 . 
Added appropriate . 
Test added for non - * imports 
LPS - 55754 Place holder src folder for compilation 
Update SpongeCommon for build fix . 
Windows vs . Unix EOL ? 
ignore Update ' modules / apps / foundation / roles / . 
Sync 
Added log entry 
add type icon with retina support 
Fixes necessary to run with / bin / sh under Solaris 
6dd8a93 9d73409 
Fixing tests on maven 
0d584dd2f 83a3538a1 
changes 
upgrade to jboss - parent 14 
updates to logo sizes 
Made the popup a littler wider to accomodate for wider text 
Source formatting 
Updating Alloy 
bump to 1 . 3 . 0 - rc0 
e46d7ee5 42a43d5c 
Fix PickBlock ' ghost item ' bug when picking with a item selected . 
fix log - seal allocation 
Update . 
rename again . 
Record 
ignore Update ' modules / apps / foundation / contacts / . 
mac natives 
Made it simpler to use without extending 
ignore Update ' modules / apps / collaboration / document - library / . 
ignore Update ' modules / apps / collaboration / message - boards / . 
dll stuff 
typo corrected 
check that the provided SAS is not null before validation . 
SNAPSHOT 
Record 
ignore Update ' modules / apps / foundation / frontend - js / . 
Upgrade wrapper to 2 . 10 
Item removed from ignoreList 
increase operation duration to fail before completion . 
fix issue # 21 
5dc3da1 8b2373a 
clean up ski file 
Smack 4 . 1 . 0 - rc2 - SNAPSHOT 
mac natives . . . 
Update git ignore 
Updated changelog 
Add image of installing mat plugin 
LEP - 1234 
i had removed - ea from the java command line because I was having trouble with an fvec parse assertion error ( unknown ) accidently pushed . 
Record 
ce24ef404a 28cb791d0d 
Kill an un - needed / un - used __init__ . 
Krakatau update 
Ignore bin and gen 
JSON file type needed ( IDEADEV - 14978 ) 
switch experiment 
update to latest FastAdapter 
update screenshots 
Removed public from WebElementCreator 
 . 
LPS - 51736 SF 
LPS - 61324 Ignore theme build files 
Refactored quartz plugin . 
update native lib 
 / / github . com / douglascrockford / JSON - java / pull / 170 
 ' curator - 1 . 2 . 4 - SNAPSHOT ' . 
setting version to 1 . 0 . 145 
ignore Update ' modules / apps / collaboration / message - boards / . 
update NEWS 
Update readme . md 
Update spring dependency from 1 . 4 . 0 . 
Fail build on warning 
Source formatting 
Fixing phpunit invocation 
testing if docker pull is necessary 
Make gradlew executable in Lazybones templates . 
bump common 
ignore Update ' modules / apps / foundation / portal - template / . 
d7d0749 4440a82 
Name the NewThreadScheduler threads 
 < No Comment Entered > 
38e6e4e 9cecf14 
Divider 
Update xml files 
 / / github . com / phonegap / phonegap - plugins / issues / 225 ) . 
fix 
3ddd9db268 a153fa1d04 
ratings - api 2 . 0 . 0 packageinfo 
Ticket # 1779 
Add note about which files need to be edited when updating the version number 
Removed leftover name field 
updated version 
ignore Update ' modules / apps / collaboration / wiki / . 
ASM sources updated ( patch included ) ; patched class recompiled 
de - activate makefile 
update apk 
 / / hazelcast . googlecode . com / svn / trunk @ 1767 3f8e66b6 - ca9d - 11dd - a2b5 - e5f827957e07 
Added Travis instruction corresponding to master branch setup . 
Update ReadMe . md 
removed reliance on compass watch for site to run 
update multiwords . txt 
aabf7a5 d8481f9 
Record 
Pushed 2 . 8 . 1 again , fixed a small UI issue . 
Use known - good locale when doing jflex codegen 
shorter unique key 
Set UTF - 8 encoding on compiler . 
b9e90a3 4879f1f 
call to gradle wrapper in travis . yml 
Need stl exceptions , still will break on jnigen ( BulletBuild . java ) 
Forgot call to super 
new root CA cert store based on latest Debian certs 
StdInvocation needs to take additional arguments 
use union merges for NEWS file 
JARs required to build & run Checkstyle . 
LPS - 66595 Trigger deployment of modules for WEB - INF / lib 
Upgrade Shadow plugin . 
Update to android gradle plugin 1 . 5 . 0 . 
Update README . md 
Bump the version number to v2 . 2b4 
Revert previous commit and going back to legacy infrasturcture . 
LPS - 63269 SF 
enable security manager in tests 
13c0552 3b723ac 
removed @ Ignore tag from JCacheClientListenerTest 
remove obsolete closes 
windows binary files for libsvm 2 . 9 release 
rm 
e63dacf ba5837e 
added - server option to application . ini by default 
6d166b7 fb24279 
remove x attribute of java file 
ignore Update ' modules / apps / web - experience / export - import / . 
template project initial 
Changed Android build tools and SDK version for TravisCI 
release 1 . 1 . 17 
Update discovery to 1 . 26 
Duplicates searcher UI redesigned 
Version 1 . 0 released ! 
updated CHANGES 
checkstyle tweaks 
a1b1355 f7b6dad 
ef7f2b4 c931cc0 
Update the year for the manual . 
c 
LPS - 61099 These are already the default values 
Specify generic type parameter 
changed build target 
Modify changelog 
 ' 1 . 56 . 50 - SNAPSHOT ' . 
ignore Update ' modules / apps / web - experience / site / . 
ignore Update ' modules / apps / foundation / login / . 
ae77f6b5 e08844d3 
10dcdb95f 0baa41919 
60a27a9 76bf8cc 
fixed FileUtil # equals 
ignore Update ' modules / apps / collaboration / blogs / . 
Update CHANGELOG . md 
ignore Update ' modules / apps / screens / . 
add apn setting parameters , and set apn parameters to bp 
e1b9833 1582b1d 
Roll to android build plugin 2 . 2 . 0 - rc2 . 
Build break due to a useless string resource ' app_name ' 
use most recent gradle 2 . 3 nightly snapshot version of Tooling API 
Gotta import lodash 
Prevented resetting the delay from throwing an exception when running in a war 
DO NOT MERGE Tweak overscroll 
added localbox . info to the topdomains of the config file , i think it ' s better for testing 
Revert " Updated gitignore for me " 
LPS - 56041 Add required file 
Hide widget that are too large 
Record 
Updated changelog 
ignore Update ' modules / apps / foundation / portal - remote / . 
New certs that won ' t expire for 10 years ( JM - 397 ) . 
Add STORM - 2063 to CHANGELOG 
Update common ref 
LPS - 46312 Suppress warning 
updated version code 
Fixed Issue # 22 
fix jdk - version for eclipse - plugin 
Revert " Revert " Merge pull request # 9 from square / riyazdf / drop - metadata - col " 
README version update 
remove unnecessary semicolon 
ca2b00c f228bdc 
merged with newest master 
LPS - 54998 SF 
getConnection if missing in calcbase url R 
Added . 
Update common for task disabling . 
SEMVER auto 
Update owncloud library reference 
SEXP strings should be serialized to JSON using UTF - 8 encoding 
Remove unused import 
 / / issues . apache . org / bugzilla / show_bug . cgi ? id = 47824 
Update NEWS file for 0 . 15 . 6 
cp 
Deleting the undeleted empty test result file . 
change travis script 
LPS - 48204 No need to reset sb at the end 
LPS - 56065 SF 
return actual value of isLocal ( ) in command line args 
Remove the mem . h2 . db file 
Make android / wait_for_emulator executable 
Update revision to 19 . 
meteor / AWSCloudFormation added to validation list 
Whitespace police 
5a6d521 f555bf6 
Update SpongeCommon ref 
c2fd6c756 6ac0248ef 
LPS - 46191 Move the icon files to the new web module 
updated wiki doco 
Changed to use the option " Auto - Detect " by default . 
work on 3 . 2 . 1 started 
Updated Common Ref . 
Fixed user property 
Fixed mget test which used deprecated refresh flag 
Completely reverted change on log4j dependency . 
add 0 . 4 . 1 . 2 tag 
note about bugfix for 724573 
Set input type on RemoteInputView 
Push version to 12 - beta9 , 230 . 
Cleanup ( dictionary ) 
removed osgi integration temporarily from build - - it is missing code after migrating over from apoc - bundle 
LPS - 48133 update SDK 
JAL 59 - Add new images 
Record 
updated images for documentation 
resize 
7b1cece51 8a28dd16b 
c548ff2 3f67a18 
whups 
Follow the include style used elsewhere in the library 
White - space change to close pull requests 
368c332 abd6c27 
Updated Studio with new bookmarks + interruptible commands 
Fix error in javadoc sample 
LRQA - 20468 prep next 
Updating Alloy to rev . 81636 
trying out shippable 
LPS - 45010 Fix typo 
add STORM - 790 to changelog 
fixed typo 
adc97d5 8f8018c 
ignore Update ' modules / apps / collaboration / mentions / . 
755f402 c1bcdbb 
b2c4f0b cbe67d5 
LPS - 60556 prep next 
Bump SpongeCommon reference . 
Prepare version 25 - beta4 . 
libexif is now libjhead 
bump required packrat version 
Use Dispose instead of Close for portability 
Add PutObjectStoreDirHere to . 
ignore Update ' modules / apps / collaboration / blogs / . 
0ef12ae0 9eea6f0 
Added TODO as a reminder to refactor / externalise an existing SQL template 
Update to rest - client 03313f170403d5d25d066c3ae28bc6294e285ac1 . 
remove one test file 
Remove ` data ` from . 
LPS - 14413 pdfbox dependency 
Removed commented out code . 
cleanup 
update changelog 
Fix bbb - record - - republish 
correction to toc to add rtut 
add storm - core / dependency - reduced - pom . 
upgrade readme version 
add missing updateConstraints ( ) 
prepare for next development iteration 
set build tools and sdk versions 
notify build failures to ri - dev @ ning . com 
3beaf91 878f6b5 
pipefail was removed to allow avoid failues by ' | cat ' 
LPS - 41246 SF 
Use ANDROID_NDK instead of ANDROID_NDK_HOME ( that ' s what the build script uses ) 
update Changes . md 
adding groups in the . 
Add - e - B to maven build of Travis 
LRQA - 26247 prep next , use latest 
Rewording 1 . 1 . 0 release notes in CHANGES . md 
release 0 . 5 . 2 
test lately fails occasionally on the build server so give it some more time 
LPS - 14912 - Source formatting 
Update profiles . properties 
Translated using Weblate ( Polish ) 
Minor formatting fix . 
Copyright notice on DMG background was a little off vertically . 
minor fix to Notice . md 
THANK YOU flies out to @ d - mariano ! 
correct null + String to not throw an NPE 
Imports 
use generified jdom 1 . 1 
ignore Update ' modules / apps / foundation / portal - search / . 
Source formatting 
Update BuildCraftEnergy . java 
Make version final . 
HttpClient SSL buffer size fix 
regenerate gradle - wrapper . jar with 1 . 9 - rc - 4 
bump version 
LPS - 56081 sdk 
LPS - 45779 SF 
016ea9119 7c3b419e1 
typo 
dont cache netbeans folder anymore 
251384a d672475 
I am reduced to jiggling the handles of Maven . 
Added STORM - 912 to Changelog 
238147150 2df0cbe9c 
cleanup 
ignore Update ' modules / apps / collaboration / comment / . 
Upgraded parent version . 
Change default ` activeOpacity ` to 0 . 2 to match iOS 
adjusting changes . txt 
Restore original ianal - maven - plugin config ( changed by mistake in a7d325b ) 
add kdiff orig merge files to gitignore 
Use JDK6 for Android compatibility . 
Disable buildNativeProjects 
Record 
Increase timeout waiting for snapshot to complete in batchingShardUpdateTaskTest 
tests for receiving authorization requests 
Added Cross Site Scripting ( DOM ) 
Make isSlopeOverride ( ) getter public . 
Source formatting 
Small update . 
Documentation 
trivial tweak 
Update README . md 
 / / www . jetbrainsdotNet / jira / browse / IDEADEV - 1428 fixed 
Add Eclipse 4 . 5 new workspace folder to . 
Updated gradle build tools 
Added idea output directory to . 
ignore Update ' modules / apps / foundation / server / . 
LPS - 47243 Prevents mobile site selector link from shifting position after tap 
Remove trailing space to please Checkstyle and Gump . 
fix groovydoc task 
Upgrade to parent POM version 30 
Dont generate so for main library 
ignore Update ' modules / apps / web - experience / journal / . 
fixing syncDoc task to avoid up - to - date message only because target directory already exists 
LPS - 56639 Update packageinfo 
Restore import 
Add . 
cbe6824d aee430a5 
logging stuff 1 . 
Update build . gralde with the next version name 
still need a res dir to prevent eclipse from freaking out 
09fdc15 6040bd4 
Added a new high dpi icon , and an updated version of the medium dpi version . 
Added toString to ToroDocument 
LPS - 68289 Activate HibernateUnexpectedRowCountAspect on CI . 
update http - client , fixes race conditions 
Adding . 
char reading test 
LPS - 5539 Source Formating . 
README . md modified . 
release 1 . 0 
acknowledge bashisms 
Remove portrait restriction in the SampleActivity declaration 
Fixed networker crash due to threading bug 
small fix 
Make sure $ BAZEL is set when ` . 
none 
Prepared 2 . 0 . 8 release 
Modified test Java link in default . pdf 
LPS - 61420 prep next 
50b65aa 0c19b83 
To JB dictionary 
01017cd 161dc80 
Prevent reflective instantiation by masochists . 
ignore Update ' modules / apps / collaboration / message - boards / . 
Fixed a bug with notification clipping 
Make sure . 
API image for wiki page 
Add missing LL orientation . 
ignore Update ' modules / apps / collaboration / flags / . 
LPS - 43557 Bnd configuration 
Make provided scope transitive 
Update KnownIssues . md 
Remove dist version suffix 
5dfccc3 dd3a021 
remove DroidPlugin form apitest 
LPS - 55635 sdk 
If " Pulse notification light " is off , don ' t flash the LED even once . 
Remove REE also . 
Add examples of ack and confirming 
Displayed a sample image properly . 
LPS - 58116 prep next 
bump equalsverifier version 
IDEADEV - 89 
renamed files 
Increment version to 3 . 2 . 2 . BUILD - SNAPSHOT 
LPS - 69371 are you sure it needs to be part of the Slim profile ? 
Revert " LPS - 47505 " 
Ignore DS_store . 
support swipe down to dismiss 
Move to NOPASS for now since movie name parsing is broken 
old parameter was removed , # 712 
Secondary constructors are not there any more 
Fix build script - - there is no readlink - f on macOS . 
LPS - 48093 - Source formatting 
Disable clear checkbox on import 
ignore Update ' modules / apps / sync / . 
update core module 
LPS - 38180 SF 
LRQA - 28321 prep next , use latest 
Updated the sample APK 
Add linechart wiki 
4001559 d2453f0 
Add javadoc task , using self - built jar of javadoc - sbt 
ignore Update ' modules / apps / foundation / portal - security / . 
5f19073 cbf026f 
add dubbo - maven 
ignore Update ' modules / apps / foundation / contacts / . 
Update ' modules / apps / foundation / expando / . 
added dependencies to the jar task of the client package 
Upgrade to Airbase 27 
making EventListener an interface to be compliant with 
HHH - 5617 - Migrate to Git for source control 
ed17fcea 2c08e3dd 
adds STORM - 1409 
7d18cfc ef41afe 
Update version to 2 . 1 . 0 
gson v2 + 
d7449b4 c464339 
Adding missing gradle library . 
Initial commit 
enable GL rendering of launch background 
LaTeX endpoint should be POST , not GET 
Update README . md 
update build . properties file to 2 . 3 M2 
Update ' modules / apps / foundation / portal - scheduler / . 
088abd3 c04e11f 
Small fix . 
ignore Update ' modules / apps / web - experience / portlet - configuration / . 
ignore Update ' modules / apps / collaboration / wiki / . 
Ignore . 
Update README . md 
Enable parsing result check 
Cleanup 
Update README . md 
Add to clean . 
Changed version to beta 
We ' re 4 . 7 now 
7a91def ce4eead 
Record 
add known bug 
Upgrade to Flow 0 . 3 . 15 
GRAILS - 5691 - remove some code that was accidentally left in the last commit 
Add build status 
removed obsolete icon 
added travis - ci support 
No longer needed , as it will be a random port 
removed Rakefile . 
Added gitignore file . 
fix LruActionTracer . class doJob . method bug for mlock . notify not work and mIsRunning always be true 
LPS - 44237 fix bad rename 
Fixed default focused element for credentials dialog opening ( password is focused if username is disabled ) 
Updated Heroku java version . 
switch appveyour build to jdk8 ( jdk7 didn ' t install correctly ) 
revert committed configuration 
Update README . md 
Moving back to Scala 2 . 8 . 1 - tests are breaking 
592b822 8659330 
Updated demo art 
LPS - 35472 Add help message for structures 
Update SpongeCommon for tileentity activation feature . 
Upgrade Ant to 1 . 9 . 6 
